# Typewriter sounds
WAV snd_dialog_typewriter1 "sfx/dialogs/typewriter1_resampled.wav" XGM2
WAV snd_dialog_typewriter2 "sfx/dialogs/typewriter2_resampled.wav" XGM2
WAV snd_dialog_typewriter3 "sfx/dialogs/typewriter3_resampled.wav" XGM2
WAV snd_dialog_typewriter4 "sfx/dialogs/typewriter4_resampled.wav" XGM2
WAV snd_dialog_typewriter5 "sfx/dialogs/typewriter5_resampled.wav" XGM2
WAV snd_dialog_typewriter6 "sfx/dialogs/typewriter6_resampled.wav" XGM2
WAV snd_dialog_typewriter7 "sfx/dialogs/typewriter7_resampled.wav" XGM2
WAV snd_dialog_typewriter8 "sfx/dialogs/typewriter8_resampled.wav" XGM2

# Woman sounds (A-Z)
WAV snd_dialog_woman_A "sfx/dialogs/woman/A_resampled.wav" XGM2
WAV snd_dialog_woman_B "sfx/dialogs/woman/B_resampled.wav" XGM2
WAV snd_dialog_woman_C "sfx/dialogs/woman/C_resampled.wav" XGM2
WAV snd_dialog_woman_D "sfx/dialogs/woman/D_resampled.wav" XGM2
WAV snd_dialog_woman_E "sfx/dialogs/woman/E_resampled.wav" XGM2
WAV snd_dialog_woman_F "sfx/dialogs/woman/F_resampled.wav" XGM2
WAV snd_dialog_woman_G "sfx/dialogs/woman/G_resampled.wav" XGM2
WAV snd_dialog_woman_H "sfx/dialogs/woman/H_resampled.wav" XGM2
WAV snd_dialog_woman_I "sfx/dialogs/woman/I_resampled.wav" XGM2
WAV snd_dialog_woman_J "sfx/dialogs/woman/J_resampled.wav" XGM2
WAV snd_dialog_woman_K "sfx/dialogs/woman/K_resampled.wav" XGM2
WAV snd_dialog_woman_L "sfx/dialogs/woman/L_resampled.wav" XGM2
WAV snd_dialog_woman_M "sfx/dialogs/woman/M_resampled.wav" XGM2
WAV snd_dialog_woman_N "sfx/dialogs/woman/N_resampled.wav" XGM2
WAV snd_dialog_woman_O "sfx/dialogs/woman/O_resampled.wav" XGM2
WAV snd_dialog_woman_P "sfx/dialogs/woman/P_resampled.wav" XGM2
WAV snd_dialog_woman_Q "sfx/dialogs/woman/Q_resampled.wav" XGM2
WAV snd_dialog_woman_R "sfx/dialogs/woman/R_resampled.wav" XGM2
WAV snd_dialog_woman_S "sfx/dialogs/woman/S_resampled.wav" XGM2
WAV snd_dialog_woman_T "sfx/dialogs/woman/T_resampled.wav" XGM2
WAV snd_dialog_woman_U "sfx/dialogs/woman/U_resampled.wav" XGM2
WAV snd_dialog_woman_V "sfx/dialogs/woman/V_resampled.wav" XGM2
WAV snd_dialog_woman_W "sfx/dialogs/woman/W_resampled.wav" XGM2
WAV snd_dialog_woman_X "sfx/dialogs/woman/X_resampled.wav" XGM2
WAV snd_dialog_woman_Y "sfx/dialogs/woman/Y_resampled.wav" XGM2
WAV snd_dialog_woman_Z "sfx/dialogs/woman/Z_resampled.wav" XGM2

# Man sounds (A-Z)
WAV snd_dialog_man_A "sfx/dialogs/man/A_resampled.wav" XGM2
WAV snd_dialog_man_B "sfx/dialogs/man/B_resampled.wav" XGM2
WAV snd_dialog_man_C "sfx/dialogs/man/C_resampled.wav" XGM2
WAV snd_dialog_man_D "sfx/dialogs/man/D_resampled.wav" XGM2
WAV snd_dialog_man_E "sfx/dialogs/man/E_resampled.wav" XGM2
WAV snd_dialog_man_F "sfx/dialogs/man/F_resampled.wav" XGM2
WAV snd_dialog_man_G "sfx/dialogs/man/G_resampled.wav" XGM2
WAV snd_dialog_man_H "sfx/dialogs/man/H_resampled.wav" XGM2
WAV snd_dialog_man_I "sfx/dialogs/man/I_resampled.wav" XGM2
WAV snd_dialog_man_J "sfx/dialogs/man/J_resampled.wav" XGM2
WAV snd_dialog_man_K "sfx/dialogs/man/K_resampled.wav" XGM2
WAV snd_dialog_man_L "sfx/dialogs/man/L_resampled.wav" XGM2
WAV snd_dialog_man_M "sfx/dialogs/man/M_resampled.wav" XGM2
WAV snd_dialog_man_N "sfx/dialogs/man/N_resampled.wav" XGM2
WAV snd_dialog_man_O "sfx/dialogs/man/O_resampled.wav" XGM2
WAV snd_dialog_man_P "sfx/dialogs/man/P_resampled.wav" XGM2
WAV snd_dialog_man_Q "sfx/dialogs/man/Q_resampled.wav" XGM2
WAV snd_dialog_man_R "sfx/dialogs/man/R_resampled.wav" XGM2
WAV snd_dialog_man_S "sfx/dialogs/man/S_resampled.wav" XGM2
WAV snd_dialog_man_T "sfx/dialogs/man/T_resampled.wav" XGM2
WAV snd_dialog_man_U "sfx/dialogs/man/U_resampled.wav" XGM2
WAV snd_dialog_man_V "sfx/dialogs/man/V_resampled.wav" XGM2
WAV snd_dialog_man_W "sfx/dialogs/man/W_resampled.wav" XGM2
WAV snd_dialog_man_X "sfx/dialogs/man/X_resampled.wav" XGM2
WAV snd_dialog_man_Y "sfx/dialogs/man/Y_resampled.wav" XGM2
WAV snd_dialog_man_Z "sfx/dialogs/man/Z_resampled.wav" XGM2

# Deep sounds (A-Z)
WAV snd_dialog_deep_A "sfx/dialogs/deep/A_resampled.wav" XGM2
WAV snd_dialog_deep_B "sfx/dialogs/deep/B_resampled.wav" XGM2
WAV snd_dialog_deep_C "sfx/dialogs/deep/C_resampled.wav" XGM2
WAV snd_dialog_deep_D "sfx/dialogs/deep/D_resampled.wav" XGM2
WAV snd_dialog_deep_E "sfx/dialogs/deep/E_resampled.wav" XGM2
WAV snd_dialog_deep_F "sfx/dialogs/deep/F_resampled.wav" XGM2
WAV snd_dialog_deep_G "sfx/dialogs/deep/G_resampled.wav" XGM2
WAV snd_dialog_deep_H "sfx/dialogs/deep/H_resampled.wav" XGM2
WAV snd_dialog_deep_I "sfx/dialogs/deep/I_resampled.wav" XGM2
WAV snd_dialog_deep_J "sfx/dialogs/deep/J_resampled.wav" XGM2
WAV snd_dialog_deep_K "sfx/dialogs/deep/K_resampled.wav" XGM2
WAV snd_dialog_deep_L "sfx/dialogs/deep/L_resampled.wav" XGM2
WAV snd_dialog_deep_M "sfx/dialogs/deep/M_resampled.wav" XGM2
WAV snd_dialog_deep_N "sfx/dialogs/deep/N_resampled.wav" XGM2
WAV snd_dialog_deep_O "sfx/dialogs/deep/O_resampled.wav" XGM2
WAV snd_dialog_deep_P "sfx/dialogs/deep/P_resampled.wav" XGM2
WAV snd_dialog_deep_Q "sfx/dialogs/deep/Q_resampled.wav" XGM2
WAV snd_dialog_deep_R "sfx/dialogs/deep/R_resampled.wav" XGM2
WAV snd_dialog_deep_S "sfx/dialogs/deep/S_resampled.wav" XGM2
WAV snd_dialog_deep_T "sfx/dialogs/deep/T_resampled.wav" XGM2
WAV snd_dialog_deep_U "sfx/dialogs/deep/U_resampled.wav" XGM2
WAV snd_dialog_deep_V "sfx/dialogs/deep/V_resampled.wav" XGM2
WAV snd_dialog_deep_W "sfx/dialogs/deep/W_resampled.wav" XGM2
WAV snd_dialog_deep_X "sfx/dialogs/deep/X_resampled.wav" XGM2
WAV snd_dialog_deep_Y "sfx/dialogs/deep/Y_resampled.wav" XGM2
WAV snd_dialog_deep_Z "sfx/dialogs/deep/Z_resampled.wav" XGM2
