# Typewriter sounds
WAV snd_dialog_typewriter1 "Sound/Dialogs/typewriter1.wav" XGM2
WAV snd_dialog_typewriter2 "Sound/Dialogs/typewriter2.wav" XGM2
WAV snd_dialog_typewriter3 "Sound/Dialogs/typewriter3.wav" XGM2
WAV snd_dialog_typewriter4 "Sound/Dialogs/typewriter4.wav" XGM2
WAV snd_dialog_typewriter5 "Sound/Dialogs/typewriter5.wav" XGM2
WAV snd_dialog_typewriter6 "Sound/Dialogs/typewriter6.wav" XGM2
WAV snd_dialog_typewriter7 "Sound/Dialogs/typewriter7.wav" XGM2
WAV snd_dialog_typewriter8 "Sound/Dialogs/typewriter8.wav" XGM2

# Woman sounds (A-Z)
WAV snd_dialog_woman_A "Sound/Dialogs/woman/A.wav" XGM2
WAV snd_dialog_woman_B "Sound/Dialogs/woman/B.wav" XGM2
WAV snd_dialog_woman_C "Sound/Dialogs/woman/C.wav" XGM2
WAV snd_dialog_woman_D "Sound/Dialogs/woman/D.wav" XGM2
WAV snd_dialog_woman_E "Sound/Dialogs/woman/E.wav" XGM2
WAV snd_dialog_woman_F "Sound/Dialogs/woman/F.wav" XGM2
WAV snd_dialog_woman_G "Sound/Dialogs/woman/G.wav" XGM2
WAV snd_dialog_woman_H "Sound/Dialogs/woman/H.wav" XGM2
WAV snd_dialog_woman_I "Sound/Dialogs/woman/I.wav" XGM2
WAV snd_dialog_woman_J "Sound/Dialogs/woman/J.wav" XGM2
WAV snd_dialog_woman_K "Sound/Dialogs/woman/K.wav" XGM2
WAV snd_dialog_woman_L "Sound/Dialogs/woman/L.wav" XGM2
WAV snd_dialog_woman_M "Sound/Dialogs/woman/M.wav" XGM2
WAV snd_dialog_woman_N "Sound/Dialogs/woman/N.wav" XGM2
WAV snd_dialog_woman_O "Sound/Dialogs/woman/O.wav" XGM2
WAV snd_dialog_woman_P "Sound/Dialogs/woman/P.wav" XGM2
WAV snd_dialog_woman_Q "Sound/Dialogs/woman/Q.wav" XGM2
WAV snd_dialog_woman_R "Sound/Dialogs/woman/R.wav" XGM2
WAV snd_dialog_woman_S "Sound/Dialogs/woman/S.wav" XGM2
WAV snd_dialog_woman_T "Sound/Dialogs/woman/T.wav" XGM2
WAV snd_dialog_woman_U "Sound/Dialogs/woman/U.wav" XGM2
WAV snd_dialog_woman_V "Sound/Dialogs/woman/V.wav" XGM2
WAV snd_dialog_woman_W "Sound/Dialogs/woman/W.wav" XGM2
WAV snd_dialog_woman_X "Sound/Dialogs/woman/X.wav" XGM2
WAV snd_dialog_woman_Y "Sound/Dialogs/woman/Y.wav" XGM2
WAV snd_dialog_woman_Z "Sound/Dialogs/woman/Z.wav" XGM2

# Man sounds (A-Z)
WAV snd_dialog_man_A "Sound/Dialogs/man/A.wav" XGM2
WAV snd_dialog_man_B "Sound/Dialogs/man/B.wav" XGM2
WAV snd_dialog_man_C "Sound/Dialogs/man/C.wav" XGM2
WAV snd_dialog_man_D "Sound/Dialogs/man/D.wav" XGM2
WAV snd_dialog_man_E "Sound/Dialogs/man/E.wav" XGM2
WAV snd_dialog_man_F "Sound/Dialogs/man/F.wav" XGM2
WAV snd_dialog_man_G "Sound/Dialogs/man/G.wav" XGM2
WAV snd_dialog_man_H "Sound/Dialogs/man/H.wav" XGM2
WAV snd_dialog_man_I "Sound/Dialogs/man/I.wav" XGM2
WAV snd_dialog_man_J "Sound/Dialogs/man/J.wav" XGM2
WAV snd_dialog_man_K "Sound/Dialogs/man/K.wav" XGM2
WAV snd_dialog_man_L "Sound/Dialogs/man/L.wav" XGM2
WAV snd_dialog_man_M "Sound/Dialogs/man/M.wav" XGM2
WAV snd_dialog_man_N "Sound/Dialogs/man/N.wav" XGM2
WAV snd_dialog_man_O "Sound/Dialogs/man/O.wav" XGM2
WAV snd_dialog_man_P "Sound/Dialogs/man/P.wav" XGM2
WAV snd_dialog_man_Q "Sound/Dialogs/man/Q.wav" XGM2
WAV snd_dialog_man_R "Sound/Dialogs/man/R.wav" XGM2
WAV snd_dialog_man_S "Sound/Dialogs/man/S.wav" XGM2
WAV snd_dialog_man_T "Sound/Dialogs/man/T.wav" XGM2
WAV snd_dialog_man_U "Sound/Dialogs/man/U.wav" XGM2
WAV snd_dialog_man_V "Sound/Dialogs/man/V.wav" XGM2
WAV snd_dialog_man_W "Sound/Dialogs/man/W.wav" XGM2
WAV snd_dialog_man_X "Sound/Dialogs/man/X.wav" XGM2
WAV snd_dialog_man_Y "Sound/Dialogs/man/Y.wav" XGM2
WAV snd_dialog_man_Z "Sound/Dialogs/man/Z.wav" XGM2

# Deep sounds (A-Z)
WAV snd_dialog_deep_A "Sound/Dialogs/deep/A.wav" XGM2
WAV snd_dialog_deep_B "Sound/Dialogs/deep/B.wav" XGM2
WAV snd_dialog_deep_C "Sound/Dialogs/deep/C.wav" XGM2
WAV snd_dialog_deep_D "Sound/Dialogs/deep/D.wav" XGM2
WAV snd_dialog_deep_E "Sound/Dialogs/deep/E.wav" XGM2
WAV snd_dialog_deep_F "Sound/Dialogs/deep/F.wav" XGM2
WAV snd_dialog_deep_G "Sound/Dialogs/deep/G.wav" XGM2
WAV snd_dialog_deep_H "Sound/Dialogs/deep/H.wav" XGM2
WAV snd_dialog_deep_I "Sound/Dialogs/deep/I.wav" XGM2
WAV snd_dialog_deep_J "Sound/Dialogs/deep/J.wav" XGM2
WAV snd_dialog_deep_K "Sound/Dialogs/deep/K.wav" XGM2
WAV snd_dialog_deep_L "Sound/Dialogs/deep/L.wav" XGM2
WAV snd_dialog_deep_M "Sound/Dialogs/deep/M.wav" XGM2
WAV snd_dialog_deep_N "Sound/Dialogs/deep/N.wav" XGM2
WAV snd_dialog_deep_O "Sound/Dialogs/deep/O.wav" XGM2
WAV snd_dialog_deep_P "Sound/Dialogs/deep/P.wav" XGM2
WAV snd_dialog_deep_Q "Sound/Dialogs/deep/Q.wav" XGM2
WAV snd_dialog_deep_R "Sound/Dialogs/deep/R.wav" XGM2
WAV snd_dialog_deep_S "Sound/Dialogs/deep/S.wav" XGM2
WAV snd_dialog_deep_T "Sound/Dialogs/deep/T.wav" XGM2
WAV snd_dialog_deep_U "Sound/Dialogs/deep/U.wav" XGM2
WAV snd_dialog_deep_V "Sound/Dialogs/deep/V.wav" XGM2
WAV snd_dialog_deep_W "Sound/Dialogs/deep/W.wav" XGM2
WAV snd_dialog_deep_X "Sound/Dialogs/deep/X.wav" XGM2
WAV snd_dialog_deep_Y "Sound/Dialogs/deep/Y.wav" XGM2
WAV snd_dialog_deep_Z "Sound/Dialogs/deep/Z.wav" XGM2
