# Typewriter sounds
WAV snd_dialog_typewriter1 "sfx/dialogs/typewriter1.wav" XGM2
WAV snd_dialog_typewriter2 "sfx/dialogs/typewriter2.wav" XGM2
WAV snd_dialog_typewriter3 "sfx/dialogs/typewriter3.wav" XGM2
WAV snd_dialog_typewriter4 "sfx/dialogs/typewriter4.wav" XGM2
WAV snd_dialog_typewriter5 "sfx/dialogs/typewriter5.wav" XGM2
WAV snd_dialog_typewriter6 "sfx/dialogs/typewriter6.wav" XGM2
WAV snd_dialog_typewriter7 "sfx/dialogs/typewriter7.wav" XGM2
WAV snd_dialog_typewriter8 "sfx/dialogs/typewriter8.wav" XGM2

# Woman sounds (A-Z)
WAV snd_dialog_woman_A "sfx/dialogs/woman/A.wav" XGM2
WAV snd_dialog_woman_B "sfx/dialogs/woman/B.wav" XGM2
WAV snd_dialog_woman_C "sfx/dialogs/woman/C.wav" XGM2
WAV snd_dialog_woman_D "sfx/dialogs/woman/D.wav" XGM2
WAV snd_dialog_woman_E "sfx/dialogs/woman/E.wav" XGM2
WAV snd_dialog_woman_F "sfx/dialogs/woman/F.wav" XGM2
WAV snd_dialog_woman_G "sfx/dialogs/woman/G.wav" XGM2
WAV snd_dialog_woman_H "sfx/dialogs/woman/H.wav" XGM2
WAV snd_dialog_woman_I "sfx/dialogs/woman/I.wav" XGM2
WAV snd_dialog_woman_J "sfx/dialogs/woman/J.wav" XGM2
WAV snd_dialog_woman_K "sfx/dialogs/woman/K.wav" XGM2
WAV snd_dialog_woman_L "sfx/dialogs/woman/L.wav" XGM2
WAV snd_dialog_woman_M "sfx/dialogs/woman/M.wav" XGM2
WAV snd_dialog_woman_N "sfx/dialogs/woman/N.wav" XGM2
WAV snd_dialog_woman_O "sfx/dialogs/woman/O.wav" XGM2
WAV snd_dialog_woman_P "sfx/dialogs/woman/P.wav" XGM2
WAV snd_dialog_woman_Q "sfx/dialogs/woman/Q.wav" XGM2
WAV snd_dialog_woman_R "sfx/dialogs/woman/R.wav" XGM2
WAV snd_dialog_woman_S "sfx/dialogs/woman/S.wav" XGM2
WAV snd_dialog_woman_T "sfx/dialogs/woman/T.wav" XGM2
WAV snd_dialog_woman_U "sfx/dialogs/woman/U.wav" XGM2
WAV snd_dialog_woman_V "sfx/dialogs/woman/V.wav" XGM2
WAV snd_dialog_woman_W "sfx/dialogs/woman/W.wav" XGM2
WAV snd_dialog_woman_X "sfx/dialogs/woman/X.wav" XGM2
WAV snd_dialog_woman_Y "sfx/dialogs/woman/Y.wav" XGM2
WAV snd_dialog_woman_Z "sfx/dialogs/woman/Z.wav" XGM2

# Man sounds (A-Z)
WAV snd_dialog_man_A "sfx/dialogs/man/A.wav" XGM2
WAV snd_dialog_man_B "sfx/dialogs/man/B.wav" XGM2
WAV snd_dialog_man_C "sfx/dialogs/man/C.wav" XGM2
WAV snd_dialog_man_D "sfx/dialogs/man/D.wav" XGM2
WAV snd_dialog_man_E "sfx/dialogs/man/E.wav" XGM2
WAV snd_dialog_man_F "sfx/dialogs/man/F.wav" XGM2
WAV snd_dialog_man_G "sfx/dialogs/man/G.wav" XGM2
WAV snd_dialog_man_H "sfx/dialogs/man/H.wav" XGM2
WAV snd_dialog_man_I "sfx/dialogs/man/I.wav" XGM2
WAV snd_dialog_man_J "sfx/dialogs/man/J.wav" XGM2
WAV snd_dialog_man_K "sfx/dialogs/man/K.wav" XGM2
WAV snd_dialog_man_L "sfx/dialogs/man/L.wav" XGM2
WAV snd_dialog_man_M "sfx/dialogs/man/M.wav" XGM2
WAV snd_dialog_man_N "sfx/dialogs/man/N.wav" XGM2
WAV snd_dialog_man_O "sfx/dialogs/man/O.wav" XGM2
WAV snd_dialog_man_P "sfx/dialogs/man/P.wav" XGM2
WAV snd_dialog_man_Q "sfx/dialogs/man/Q.wav" XGM2
WAV snd_dialog_man_R "sfx/dialogs/man/R.wav" XGM2
WAV snd_dialog_man_S "sfx/dialogs/man/S.wav" XGM2
WAV snd_dialog_man_T "sfx/dialogs/man/T.wav" XGM2
WAV snd_dialog_man_U "sfx/dialogs/man/U.wav" XGM2
WAV snd_dialog_man_V "sfx/dialogs/man/V.wav" XGM2
WAV snd_dialog_man_W "sfx/dialogs/man/W.wav" XGM2
WAV snd_dialog_man_X "sfx/dialogs/man/X.wav" XGM2
WAV snd_dialog_man_Y "sfx/dialogs/man/Y.wav" XGM2
WAV snd_dialog_man_Z "sfx/dialogs/man/Z.wav" XGM2

# Deep sounds (A-Z)
WAV snd_dialog_deep_A "sfx/dialogs/deep/A.wav" XGM2
WAV snd_dialog_deep_B "sfx/dialogs/deep/B.wav" XGM2
WAV snd_dialog_deep_C "sfx/dialogs/deep/C.wav" XGM2
WAV snd_dialog_deep_D "sfx/dialogs/deep/D.wav" XGM2
WAV snd_dialog_deep_E "sfx/dialogs/deep/E.wav" XGM2
WAV snd_dialog_deep_F "sfx/dialogs/deep/F.wav" XGM2
WAV snd_dialog_deep_G "sfx/dialogs/deep/G.wav" XGM2
WAV snd_dialog_deep_H "sfx/dialogs/deep/H.wav" XGM2
WAV snd_dialog_deep_I "sfx/dialogs/deep/I.wav" XGM2
WAV snd_dialog_deep_J "sfx/dialogs/deep/J.wav" XGM2
WAV snd_dialog_deep_K "sfx/dialogs/deep/K.wav" XGM2
WAV snd_dialog_deep_L "sfx/dialogs/deep/L.wav" XGM2
WAV snd_dialog_deep_M "sfx/dialogs/deep/M.wav" XGM2
WAV snd_dialog_deep_N "sfx/dialogs/deep/N.wav" XGM2
WAV snd_dialog_deep_O "sfx/dialogs/deep/O.wav" XGM2
WAV snd_dialog_deep_P "sfx/dialogs/deep/P.wav" XGM2
WAV snd_dialog_deep_Q "sfx/dialogs/deep/Q.wav" XGM2
WAV snd_dialog_deep_R "sfx/dialogs/deep/R.wav" XGM2
WAV snd_dialog_deep_S "sfx/dialogs/deep/S.wav" XGM2
WAV snd_dialog_deep_T "sfx/dialogs/deep/T.wav" XGM2
WAV snd_dialog_deep_U "sfx/dialogs/deep/U.wav" XGM2
WAV snd_dialog_deep_V "sfx/dialogs/deep/V.wav" XGM2
WAV snd_dialog_deep_W "sfx/dialogs/deep/W.wav" XGM2
WAV snd_dialog_deep_X "sfx/dialogs/deep/X.wav" XGM2
WAV snd_dialog_deep_Y "sfx/dialogs/deep/Y.wav" XGM2
WAV snd_dialog_deep_Z "sfx/dialogs/deep/Z.wav" XGM2
