// Generated by tools/gen_choices.py from data/choices.csv — DO NOT EDIT
#ifndef _CHOICES_DATA_H_
#define _CHOICES_DATA_H_

#include "narrative/texts.h"

// Choice sets (índices en choices[])
#define ACT1_HALL_CHOICE    0

extern const ChoiceItem *choices[];

#endif // _CHOICES_DATA_H_
