// Generated by tools/gen_choices.py from data/choices.csv — DO NOT EDIT
#include <genesis.h>
#include "narrative/texts.h"
#include "narrative/choices_data.h"
#include "narrative/dialogs.h"
#include "actors/characters.h"

const ChoiceItem act1_hall_choice[] = {
    {FACE_linus, SIDE_RIGHT, DEFAULT_CHOICE_TIME, 3,
        {{ "¿Los Tejedores?", "Era mi leyenda favorita", "¿Qué pasó con ellos?"},
        { "The Weavers?", "It was my favourite legend", "What happened to them?"}}},
    {FACE_linus, SIDE_RIGHT, DEFAULT_CHOICE_TIME, 2,
        {{ "Tengo que ir a la isla", "¿Vendrías conmigo?"},
        { "I have to go to the island", "Would you come with me?"}}},
    {0, SIDE_LEFT, DEFAULT_TALK_TIME, 0, {{NULL}}} // Terminator
};

const ChoiceItem act1_test_choice[] = {
    {FACE_linus, SIDE_RIGHT, DEFAULT_CHOICE_TIME, 2,
        {{ "TEST: Probar el puzzle", "TEST: Saltar al combate"},
        { "TEST: Try the puzzle", "TEST: Skip to combat"}}},
    {0, SIDE_LEFT, DEFAULT_TALK_TIME, 0, {{NULL}}} // Terminator
};

const ChoiceItem *choices[] = {
    act1_hall_choice,   // 0
    act1_test_choice,   // 1
};
