// Auto-generated from texts.csv and clusters.csv – DO NOT EDIT
#include <genesis.h>
#include "narrative/narrative.h"
#include "actors/actors.h"

const DialogItem system_dialog[] = {
    [SYSMSG_DEMO_TITLE] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"@[The Weave@]|Demo técnica|Junio de 2025",
         "@[The Weave@]|Tech demo|June 2025"} },
    [SYSMSG_DISCLAIMER] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Los gráficos, mecánicas o sonidos|no son definitivos, ni|representan el resultado final",
         "Graphics, mechanics or sounds|aren't final, nor they|represent the final result"} },
    [SYSMSG_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [SYSMSG_CANT_USE_PATTERN] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No puedo usar ese patrón|ahora mismo",
         "I can't use that pattern|right now"} },
    [SYSMSG_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem act1_corridor[] = {
    [A1_CORRIDOR_OVERSLEPT] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Creo que he dormido demasiado|Debo llegar rápido al salón",
         "I think I've overslept|I should go to the hall quickly"} },
    [A1_CORRIDOR_MEMORIES] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Aunque siendo el día que es|este pasillo me trae|@[demasiados recuerdos@]",
         "Although in a day like this|this hallway brings back|too @[many memories@]"} },
    [A1_CORRIDOR_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_CORRIDOR_DOOR1_CHECK] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"No puedo entrar en el cuarto|de los ancianos sin su permiso",
         "I can't enter the elders' room|without their permission"} },
    [A1_CORRIDOR_DOOR2_CHECK] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Luego iré a la biblioteca|Me paso allí media vida",
         "I'll go to the library later|I spend half my life there"} },
    [A1_CORRIDOR_DOOR3_CHECK] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Luego volveré a mi cuarto|Ahora me esperan",
         "I'll go back to my room later|Now I have to go"} },
    [A1_CORRIDOR_MAP_CHECK] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Tenemos la mejor colección|de mapas de @[todos los gremios@]",
         "We have the best collection|of maps from @[all guilds@]"} },
    [A1_CORRIDOR_REVISIT_MEMORIES] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Antes de irme quiero|repasar algunos recuerdos|Se lo debo a papá",
         "Before I leave I want to|revisit some memories|I owe it to dad"} },
    [A1_CORRIDOR_TERM_2] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_CORRIDOR_BOOK_HISTORY] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Este tomo narra la historia|de nuestro gremio|desde la @[Gran Separación@]",
         "This volume narrates the history|of our guild|since the @[Great Split@]"} },
    [A1_CORRIDOR_BOOK_ENDS_WITH_FATHER] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"El último capítulo|termina con el fallecimiento|de mi padre",
         "The last chapter|ends with the passing|of my father"} },
    [A1_CORRIDOR_BOOK_MOTHER_WRITES_NEXT] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Madre dice que seré yo|el que deba escribir|el siguiente",
         "Mother says it will be me|who has to write|the next one"} },
    [A1_CORRIDOR_TERM_3] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_CORRIDOR_MYTH_COLLECTION] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Una colección de|mitos y leyendas|de los distintos gremios",
         "A collection of|myths and legends|from the different guilds"} },
    [A1_CORRIDOR_MYTH_PASTORS] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Gracias a mi padre|tenemos documentadas|las que cantaban los @[Pastores@]",
         "Thanks to my father|we have documented|those the @[Shepherds@] sang"} },
    [A1_CORRIDOR_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem act1_hall[] = {
    [A1_HALL_GUILD_YEAR] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"@[Gremio de los historiadores@]|Año 8121",
         "@[Historians guild@]|Year 8121"} },
    [A1_HALL_MONDAY_MORNING] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Lunes|Primera hora de la mañana",
         "Monday|Early morning"} },
    [A1_HALL_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HALL_CLIO_LATE] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Es tarde, Linus|Y uno no debe llegar tarde|a su cumpleaños",
         "It's late, Linus|And you shouldn't be late|at your birthday"} },
    [A1_HALL_LINUS_STRANGEST_DREAM] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"He tenido un sueño|de lo más extraño, Madre",
         "I have had the strangest|dream, Mother"} },
    [A1_HALL_SWAN_CAME] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Un @[cisne@] venía a|mi cuarto y...",
         "A @[swan@] came to my room|and..."} },
    [A1_HALL_CLIO_TELL_LATER] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Luego me lo cuentas|@[Xander@] nos espera",
         "You can tell me later|@[Xander@] is waiting for us"} },
    [A1_HALL_TERM_2] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HALL_XANDER_AWAKE] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Por fin|estás despierto, Linus",
         "At last,|you're awake Linus"} },
    [A1_HALL_LINUS_FORGIVE] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Perdóname, maestro|Un extraño sueño me ha|mantenido despierto",
         "Forgive me, master|A strange dream has|kept me awake"} },
    [A1_HALL_XANDER_YOUR_FATHERS_SON] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Ciertamente eres el|hijo de tu padre|@[Aiden@] tenía grandes sueños",
         "You are certainly your|father's son|@[Aiden@] had big dreams"} },
    [A1_HALL_XANDER_UNFULFILLED] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Y estamos aquí para hablar|sobre uno que|nunca llegó a cumplir",
         "And we are here to talk|about one that he|never achieved"} },
    [A1_HALL_LINUS_WHICH_STORY] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"He leído sus historias|mil veces|¿De cuál hablamos?",
         "I've read his stories|a thousand times|Which one is this?"} },
    [A1_HALL_XANDER_ISLAND_LEGEND] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Una que no encontrarás en|un libro. La de la isla|del @[Gremio de los Tejedores@]",
         "One you won't find in a book|The one about @[Weavers|guild@] island"} },
    [A1_HALL_TERM_3] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HALL_XANDER_ABILITY] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Según la leyenda|Fueron un gremio|capaz de tejer hechizos",
         "According to the legend|They were a guild|able to weave spells"} },
    [A1_HALL_XANDER_NOT_LEGEND] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Para él no era una leyenda|Los @[Pastores@] la cantaban|como cierta",
         "That was no legend for him|@[Shepherds@] sang it as a fact"} },
    [A1_HALL_XANDER_VANISHED] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Desaparecieron sin dejar rastro|Aunque muchos creen|que era solo un cuento",
         "They vanished without a trace|Although many believe|it was just a tale"} },
    [A1_HALL_TERM_4] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HALL_XANDER_FATHER_WANTED] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Tu padre quería encontrar|@[la isla donde vivían@]",
         "Your father wanted to find|their @[home island@]"} },
    [A1_HALL_CLIO_DESTINY] = { FACE_clio, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Nuestro destino es|documentar hechos,|no perseguirlos",
         "Our destiny is to|document facts,|not to chase them"} },
    [A1_HALL_XANDER_LINUS_AGE] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Linus tiene diecisiete años|Esa era mi edad cuando|viajé por el mundo",
         "Linus is seventeen|That was my age when|I traveled the world"} },
    [A1_HALL_XANDER_FATHERS_AGE] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Y la edad de su padre cuando|llegó aquí",
         "And his father's age when|he came to us"} },
    [A1_HALL_XANDER_BEFORE_JOINED] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Un año antes de que|le acogiéramos|como uno de los nuestros",
         "A year before we|took him as one of ours"} },
    [A1_HALL_LINUS_MOTHER] = { FACE_linus, SIDE_RIGHT, 100,
        {"Madre...",
         "Mother..."} },
    [A1_HALL_TERM_5] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HALL_CLIO_IF_XANDER_WANTS] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Si Xander lo quiere, así será|Pero no irás solo",
         "If Xander wants it that way,|so it will be|But you'll not go alone"} },
    [A1_HALL_CLIO_I_WONT_LET_YOU] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Nunca me ha gustado viajar|Pero no dejaré que vayas solo",
         "I've never liked to travel|But I won't let you go alone"} },
    [A1_HALL_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem act1_forest[] = {
    [A1_FOREST_SOME_TIME_LATER] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Algún tiempo después",
         "Some time later"} },
    [A1_FOREST_ENEMIES_APPROACHING] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Se aproximan enemigos|Tenemos que estar atentos|Quédate cerca, madre",
         "Enemies are approaching|We have to stay alert|Stay close, mother"} },
    [A1_FOREST_NOTE_ABOUT_SCENE] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"@[NOTA@]: Puede que esta escena o estos|hechizos no estén en el|juego cuando esté terminado",
         "@[NOTE@]: This scene or these|spells may not be in the|game when finished"} },
    [A1_FOREST_DEMO_REASON] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Se ha decidido incluirla|en esta demo técnica|como prueba de ciertas mecánicas",
         "It's been decided to include it|in this technical demo|as a test of certain mechanics"} },
    [A1_FOREST_PRESS_START] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Pulsa @[START@] para ver|tu inventario de hechizos",
         "Press @[START@] to view|your spell inventory"} },
    [A1_FOREST_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_FOREST_3BUTTONS] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Vaya, parece que estás usando|@[un mando de tres botones@]",
         "Oops, it seems you are using|@[a three-button controller@]"} },
    [A1_FOREST_BUTTONS_HINT] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"El juego completo necesitará|@[seis botones@], pero para esta demo|solo necesitas tres",
         "The full game will need|@[six buttons@], but for this demo|you only need three"} },
    [A1_FOREST_TERM_2] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_FOREST_THAT_HURTS] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Eso ha dolido",
         "That hurts"} },
    [A1_FOREST_THINK_BACKWARDS] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Quizá deba pensar|al revés",
         "I should maybe|think backwards"} },
    [A1_FOREST_TRY_HIDE_OR_THUNDER] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Puedo probar a esconderme|o tratar de invocar|al trueno",
         "I could try to hide|or attempt to summon|the thunder"} },
    [A1_FOREST_REVERSE_HINT] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Tengo que contraatacar|justo después de su hechizo",
         "I have to counterattack|right after their spell"} },
    [A1_FOREST_REVERSE_NOTES_COUNTER] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Si reproduzco al revés|las notas, podré|contraatacar este hechizo",
         "If I play the notes backwards|I could be able to|counter the spell"} },
    [A1_FOREST_CANT_CAST_WHILE_HIDDEN] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No puedo lanzar hechizos|si estoy escondido",
         "I can't launch spells|while hiding"} },
    [A1_FOREST_GOOD_IDEA_HIDE] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Buena idea. Así no me verán",
         "Good idea. They won't see me"} },
    [A1_FOREST_THATS_ALL] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"@[¡Esto es todo!@]|(por ahora)",
         "@[That's all!@]|(by now)"} },
    [A1_FOREST_THANKS_FOR_PLAYING] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Gracias por probar la demo técnica|Síguenos por X o BlueSky|@[@GeeseBumpsGames@]",
         "Thanks for testing our tech demo|Follow us in X or BlueSky|@[@GeeseBumpsGames@]"} },
    [A1_FOREST_TURN_OFF_CONSOLE] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Apaga tu consola|y haz algo constructivo|como jugar un poco al frontón",
         "Turn off your console|and do something constructive|like play a little racquetball"} },
    [A1_FOREST_ORGANIZE_SOCKS] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"o preparar la cena,|o organizar tu cajón de calcetines|alfabéticamente.",
         "or cook dinner,|or organize your sock drawer|alphabetically."} },
    [A1_FOREST_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem act1_bedroom[] = {
    [A1_BEDROOM_HUNDRED_YEARS] = { FACE_swan, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Han pasado ya cien años",
         "A hundred years have passed"} },
    [A1_BEDROOM_CANT_STOP_LONG] = { FACE_swan, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No podremos pararles|por mucho más tiempo",
         "We won't be able to|stop them for much longer"} },
    [A1_BEDROOM_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_BEDROOM_NEXT_MORNING] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"A la mañana siguiente...",
         "The next morning..."} },
    [A1_BEDROOM_SLEPT_BAD] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"He dormido regular esta noche|Tuve horribles pesadillas",
         "I've not slept well last night|I had terrible nightmares"} },
    [A1_BEDROOM_NO_TIME_TO_SIT] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No tengo tiempo de sentarme|@[Madre@] me espera",
         "I don't have time to sit down|@[Mother@] is waiting for me"} },
    [A1_BEDROOM_NOT_REAL] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No ha podido ser real|La ventana está cerrada",
         "It couldn't be real|The windows is closed"} },
    [A1_BEDROOM_LULLABY] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Esta es la @[nana@] que me|cantaban cada noche",
         "That's the @[lullaby@] they used|to sing to me every night"} },
    [A1_BEDROOM_TERM_2] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_BEDROOM_LEARNED_PATTERN] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Has aprendido|tu primer @[patrón@]",
         "You have learned|your first @[pattern@]"} },
    [A1_BEDROOM_ENTER_PAUSE_MENU] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Entra en el menú de|pausa para verlo",
         "Enter the pause menu|to check it out"} },
    [A1_BEDROOM_TERM_3] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_BEDROOM_MOTHER_CALLS] = { FACE_clio, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"@[Linus@], ¿dónde estás?",
         "@[Linus@], where are you?"} },
    [A1_BEDROOM_TOO_LATE] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Se me ha hecho demasiado tarde|tengo que ir al salón",
         "It's gotten too late|I need to go the hall"} },
    [A1_BEDROOM_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem act1_test[] = {
    [A1_TEST_INTRO] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Banco de pruebas|del motor de escenas",
         "TEST: Scene engine|test bench"} },
    [A1_TEST_INTRO_2] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Un menú permite probar|cada sección y volver|Botones: A=MI B=FA C=SOL|X=LA Y=SI Z=DO",
         "A menu lets you test|each section and return|Buttons: A=MI B=FA C=SOL|X=LA Y=SI Z=DO"} },
    [A1_TEST_INTRO_3] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Pulsa @[A@] para empezar",
         "Press @[A@] to start"} },
    [A1_TEST_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_TEST_HUB] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: ¿Qué sección|quieres probar?",
         "TEST: Which section|do you want to test?"} },
    [A1_TEST_DLG_CLIO] = { FACE_clio, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"TEST: Cara de Clio|a la derecha",
         "TEST: Clio face|on the right"} },
    [A1_TEST_DLG_XANDER] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Cara de Xander|a la izquierda",
         "TEST: Xander face|on the left"} },
    [A1_TEST_ANIM] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Animación de magia|lanzada por opcode del DSL",
         "TEST: Magic animation|via DSL opcode"} },
    [A1_TEST_QUIZ_Q1] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST Quiz 1 de 2:|¿Cuántas notas tiene un|patrón del jugador?",
         "TEST Quiz 1 of 2:|How many notes has|a player pattern?"} },
    [A1_TEST_QUIZ_BAD] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Respuesta incorrecta|Inténtalo otra vez",
         "TEST: Wrong answer|Try again"} },
    [A1_TEST_QUIZ_Q2] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST Quiz 2 de 2:|¿Qué hechizo es palíndromo|y no puede invertirse?",
         "TEST Quiz 2 of 2:|Which spell is a palindrome|and cannot be reversed?"} },
    [A1_TEST_QUIZ_CONF] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: ¿Estás seguro|de tu respuesta?",
         "TEST: Are you sure|about your answer?"} },
    [A1_TEST_QUIZ_OK] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: ¡Quiz superado!|Choices anidados y|reintentos funcionan",
         "TEST: Quiz passed!|Nested choices and|retries work"} },
    [A1_TEST_DEMO_CAST] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Cast scripted de @[sleep@]|(solo posible por guion)",
         "TEST: Scripted @[sleep@] cast|(script-only spell)"} },
    [A1_TEST_LIGHT_DEMO] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Cast scripted de @[luz@]|hechizo nuevo hecho con|fases declarativas",
         "TEST: Scripted @[light@] cast|new spell built from|declarative phases"} },
    [A1_TEST_PUZ_CHOICE] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: ¿Qué puzzle|quieres probar?",
         "TEST: Which puzzle|do you want to try?"} },
    [A1_TEST_PUZZLE_INTRO] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST Puzzle 1: lanza|@[trueno@], @[fuego@] y @[esconderse@]|en ese orden",
         "TEST Puzzle 1: cast|@[thunder@], @[fire@] and @[hide@]|in that order"} },
    [A1_TEST_PUZZLE_INTRO_2] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Notas: trueno MI FA SOL SOL|fuego MI FA SOL LA|esconderse FA SOL SOL FA",
         "Notes: thunder MI FA SOL SOL|fire MI FA SOL LA|hide FA SOL SOL FA"} },
    [A1_TEST_PUZZLE_INTRO_3] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Fallar un hechizo reinicia|la secuencia desde cero",
         "A wrong cast restarts|the sequence from zero"} },
    [A1_TEST_TERM_2] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_TEST_PUZ2_INTRO] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST Puzzle 2: con INVERTIDO|@[trueno@], @[luz invertida@]|y @[esconderse@]",
         "TEST Puzzle 2: with REVERSED|@[thunder@], @[reversed light@]|and @[hide@]"} },
    [A1_TEST_PUZ2_INTRO_2] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Notas: trueno MI FA SOL SOL|luz invertida DO SI LA SOL|esconderse FA SOL SOL FA",
         "Notes: thunder MI FA SOL SOL|reversed light DO SI LA SOL|hide FA SOL SOL FA"} },
    [A1_TEST_TERM_3] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_TEST_NEVER] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: ERROR|esto no debería verse",
         "TEST: ERROR|you should never see this"} },
    [A1_TEST_PUZZLE_OK] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: ¡Secuencia correcta!|La puerta se abre",
         "TEST: Correct sequence!|The door opens"} },
    [A1_TEST_COMBAT] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST Oleada 1: fantasma|clásico. Contrarresta su|trueno con SOL SOL FA MI",
         "TEST Wave 1: classic ghost|Counter its thunder|with SOL SOL FA MI"} },
    [A1_TEST_WAVE2] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST Oleada 2: fantasma con|DOS hechizos. El @[mordisco@]|NO se puede contrarrestar",
         "TEST Wave 2: ghost with|TWO spells. The @[bite@]|cannot be countered"} },
    [A1_TEST_VICTORY] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Combate superado|Volviendo al menú",
         "TEST: Combat cleared|Back to the menu"} },
    [A1_TEST_COMBAT_MENU] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: ¿Qué tipo|de combate?",
         "TEST: Which kind|of combat?"} },
    [A1_TEST_MELEE] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST Jabalíes: sin vara.|Pulsa @[A@] para golpear|Tres golpes los ahuyentan",
         "TEST Boars: no rod.|Press @[A@] to strike|Three hits drive them away"} },
    [A1_TEST_BYE] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Fin del banco de pruebas|Volviendo al dormitorio",
         "TEST: End of the test bench|Returning to the bedroom"} },
    [A1_TEST_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem *dialogs[] = {
    system_dialog,  // 0
    act1_corridor,  // 1
    act1_hall,  // 2
    act1_forest,  // 3
    act1_bedroom,  // 4
    act1_test,  // 5
};
