// Auto-generated from texts.csv and clusters.csv – DO NOT EDIT
#ifndef _TEXTS_DATA_H_
#define _TEXTS_DATA_H_

#include "narrative/texts.h"

enum SystemDialogId {
    SYSMSG_DEMO_TITLE = 0,
    SYSMSG_DISCLAIMER = 1,
    SYSMSG_TERM_1 = 2,
    SYSMSG_CANT_USE_PATTERN = 3,
    SYSMSG_COUNT = 4
};

enum Act1CorridorId {
    A1_CORRIDOR_OVERSLEPT = 0,
    A1_CORRIDOR_MEMORIES = 1,
    A1_CORRIDOR_TERM_1 = 2,
    A1_CORRIDOR_DOOR1_CHECK = 3,
    A1_CORRIDOR_DOOR2_CHECK = 4,
    A1_CORRIDOR_DOOR3_CHECK = 5,
    A1_CORRIDOR_MAP_CHECK = 6,
    A1_CORRIDOR_REVISIT_MEMORIES = 7,
    A1_CORRIDOR_TERM_2 = 8,
    A1_CORRIDOR_BOOK_HISTORY = 9,
    A1_CORRIDOR_BOOK_ENDS_WITH_FATHER = 10,
    A1_CORRIDOR_BOOK_MOTHER_WRITES_NEXT = 11,
    A1_CORRIDOR_TERM_3 = 12,
    A1_CORRIDOR_MYTH_COLLECTION = 13,
    A1_CORRIDOR_MYTH_PASTORS = 14,
    A1_CORRIDOR_COUNT = 15
};

enum Act1HallId {
    A1_HALL_GUILD_YEAR = 0,
    A1_HALL_MONDAY_MORNING = 1,
    A1_HALL_TERM_1 = 2,
    A1_HALL_CLIO_LATE = 3,
    A1_HALL_LINUS_STRANGEST_DREAM = 4,
    A1_HALL_SWAN_CAME = 5,
    A1_HALL_CLIO_TELL_LATER = 6,
    A1_HALL_TERM_2 = 7,
    A1_HALL_XANDER_AWAKE = 8,
    A1_HALL_LINUS_FORGIVE = 9,
    A1_HALL_XANDER_YOUR_FATHERS_SON = 10,
    A1_HALL_XANDER_UNFULFILLED = 11,
    A1_HALL_LINUS_WHICH_STORY = 12,
    A1_HALL_XANDER_ISLAND_LEGEND = 13,
    A1_HALL_TERM_3 = 14,
    A1_HALL_XANDER_ABILITY = 15,
    A1_HALL_XANDER_NOT_LEGEND = 16,
    A1_HALL_XANDER_VANISHED = 17,
    A1_HALL_TERM_4 = 18,
    A1_HALL_XANDER_FATHER_WANTED = 19,
    A1_HALL_CLIO_DESTINY = 20,
    A1_HALL_XANDER_LINUS_AGE = 21,
    A1_HALL_XANDER_FATHERS_AGE = 22,
    A1_HALL_XANDER_BEFORE_JOINED = 23,
    A1_HALL_LINUS_MOTHER = 24,
    A1_HALL_TERM_5 = 25,
    A1_HALL_CLIO_IF_XANDER_WANTS = 26,
    A1_HALL_CLIO_I_WONT_LET_YOU = 27,
    A1_HALL_COUNT = 28
};

enum Act1ForestId {
    A1_FOREST_SOME_TIME_LATER = 0,
    A1_FOREST_ENEMIES_APPROACHING = 1,
    A1_FOREST_NOTE_ABOUT_SCENE = 2,
    A1_FOREST_DEMO_REASON = 3,
    A1_FOREST_PRESS_START = 4,
    A1_FOREST_TERM_1 = 5,
    A1_FOREST_3BUTTONS = 6,
    A1_FOREST_BUTTONS_HINT = 7,
    A1_FOREST_TERM_2 = 8,
    A1_FOREST_THAT_HURTS = 9,
    A1_FOREST_THINK_BACKWARDS = 10,
    A1_FOREST_TRY_HIDE_OR_THUNDER = 11,
    A1_FOREST_REVERSE_HINT = 12,
    A1_FOREST_REVERSE_NOTES_COUNTER = 13,
    A1_FOREST_CANT_CAST_WHILE_HIDDEN = 14,
    A1_FOREST_GOOD_IDEA_HIDE = 15,
    A1_FOREST_THATS_ALL = 16,
    A1_FOREST_THANKS_FOR_PLAYING = 17,
    A1_FOREST_TURN_OFF_CONSOLE = 18,
    A1_FOREST_ORGANIZE_SOCKS = 19,
    A1_FOREST_COUNT = 20
};

enum Act1BedroomId {
    A1_BEDROOM_HUNDRED_YEARS = 0,
    A1_BEDROOM_CANT_STOP_LONG = 1,
    A1_BEDROOM_TERM_1 = 2,
    A1_BEDROOM_NEXT_MORNING = 3,
    A1_BEDROOM_SLEPT_BAD = 4,
    A1_BEDROOM_NO_TIME_TO_SIT = 5,
    A1_BEDROOM_NOT_REAL = 6,
    A1_BEDROOM_LULLABY = 7,
    A1_BEDROOM_TERM_2 = 8,
    A1_BEDROOM_LEARNED_PATTERN = 9,
    A1_BEDROOM_ENTER_PAUSE_MENU = 10,
    A1_BEDROOM_TERM_3 = 11,
    A1_BEDROOM_MOTHER_CALLS = 12,
    A1_BEDROOM_TOO_LATE = 13,
    A1_BEDROOM_PORTRAIT_PH = 14,
    A1_BEDROOM_SHELF_PH = 15,
    A1_BEDROOM_CHEST_PH = 16,
    A1_BEDROOM_COUNT = 17
};

enum Act1TestId {
    A1_TEST_INTRO = 0,
    A1_TEST_INTRO_2 = 1,
    A1_TEST_INTRO_3 = 2,
    A1_TEST_TERM_1 = 3,
    A1_TEST_HUB = 4,
    A1_TEST_DLG_CLIO = 5,
    A1_TEST_DLG_XANDER = 6,
    A1_TEST_ANIM = 7,
    A1_TEST_QUIZ_Q1 = 8,
    A1_TEST_QUIZ_BAD = 9,
    A1_TEST_QUIZ_Q2 = 10,
    A1_TEST_QUIZ_CONF = 11,
    A1_TEST_QUIZ_OK = 12,
    A1_TEST_DEMO_CAST = 13,
    A1_TEST_LIGHT_DEMO = 14,
    A1_TEST_PUZ_CHOICE = 15,
    A1_TEST_PUZZLE_INTRO = 16,
    A1_TEST_PUZZLE_INTRO_2 = 17,
    A1_TEST_PUZZLE_INTRO_3 = 18,
    A1_TEST_TERM_2 = 19,
    A1_TEST_PUZ2_INTRO = 20,
    A1_TEST_PUZ2_INTRO_2 = 21,
    A1_TEST_TERM_3 = 22,
    A1_TEST_NEVER = 23,
    A1_TEST_PUZZLE_OK = 24,
    A1_TEST_COMBAT = 25,
    A1_TEST_WAVE2 = 26,
    A1_TEST_VICTORY = 27,
    A1_TEST_COMBAT_MENU = 28,
    A1_TEST_MELEE = 29,
    A1_TEST_DEFEAT = 30,
    A1_TEST_BYE = 31,
    A1_TEST_COUNT = 32
};

enum Act1CoastId {
    A1_COAST_ARRIVE = 0,
    A1_COAST_COMBAT = 1,
    A1_COAST_HEAL = 2,
    A1_COAST_ONWARD = 3,
    A1_COAST_DEFEAT = 4,
    A1_COAST_TREE = 5,
    A1_COAST_COUNT = 6
};

enum Act1HutId {
    A1_HUT_ENTER = 0,
    A1_HUT_LOOM = 1,
    A1_HUT_STAFF = 2,
    A1_HUT_SYSTEM = 3,
    A1_HUT_LEAVE = 4,
    A1_HUT_DEBRIS = 5,
    A1_HUT_THREADS = 6,
    A1_HUT_BOBBIN = 7,
    A1_HUT_SHADOW = 8,
    A1_HUT_COUNT = 9
};

enum Act1ReturnId {
    A1_RETURN_START = 0,
    A1_RETURN_BOARS = 1,
    A1_RETURN_DEFEAT = 2,
    A1_RETURN_GHOSTS = 3,
    A1_RETURN_DONE = 4,
    A1_RETURN_BOBBIN_HINT = 5,
    A1_RETURN_DARKOUT = 6,
    A1_RETURN_SYSTEM_DARK = 7,
    A1_RETURN_BOBBIN_DARK = 8,
    A1_RETURN_RELIT = 9,
    A1_RETURN_COUNT = 10
};

enum Act1CoastEndId {
    A1_END_DIALOG = 0,
    A1_END_FIN = 1,
    A1_END_PAUSE = 2,
    A1_END_BOBBIN = 3,
    A1_END_COUNT = 4
};

enum DialogSetId {
    SYSTEM_DIALOG,  // 0
    ACT1_CORRIDOR,  // 1
    ACT1_HALL,  // 2
    ACT1_FOREST,  // 3
    ACT1_BEDROOM,  // 4
    ACT1_TEST,  // 5
    ACT1_COAST,  // 6
    ACT1_HUT,  // 7
    ACT1_RETURN,  // 8
    ACT1_COAST_END,  // 9
    DIALOG_SET_COUNT
};

#endif // _TEXTS_DATA_H_
