// Auto-generated from texts.csv and clusters.csv – DO NOT EDIT
#include <genesis.h>
#include "narrative/narrative.h"
#include "actors/actors.h"

const DialogItem system_dialog[] = {
    [SYSMSG_DEMO_TITLE] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"@[The Weave@]|Demo técnica|Junio de 2025",
         "@[The Weave@]|Tech demo|June 2025"} },
    [SYSMSG_DISCLAIMER] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Los gráficos, mecánicas o sonidos|no son definitivos, ni|representan el resultado final",
         "Graphics, mechanics or sounds|aren't final, nor they|represent the final result"} },
    [SYSMSG_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [SYSMSG_CANT_USE_PATTERN] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No puedo usar ese patrón|ahora mismo",
         "I can't use that pattern|right now"} },
    [SYSMSG_NOTE_LOCKED] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Aún no soy capaz|de tocar esa nota",
         "I'm not yet able|to play that note"} },
    [SYSMSG_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem act1_corridor[] = {
    [A1_CORRIDOR_OVERSLEPT] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Creo que he dormido demasiado|Debo llegar rápido al salón",
         "I think I've overslept|I should go to the hall quickly"} },
    [A1_CORRIDOR_MEMORIES] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Aunque siendo el día que es|este pasillo me trae|@[demasiados recuerdos@]",
         "Although in a day like this|this hallway brings back|too @[many memories@]"} },
    [A1_CORRIDOR_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_CORRIDOR_DOOR1_CHECK] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"No puedo entrar en el cuarto|de los ancianos sin su permiso",
         "I can't enter the elders' room|without their permission"} },
    [A1_CORRIDOR_DOOR2_CHECK] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Luego iré a la biblioteca|Me paso allí media vida",
         "I'll go to the library later|I spend half my life there"} },
    [A1_CORRIDOR_DOOR3_CHECK] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Luego volveré a mi cuarto|Ahora me esperan",
         "I'll go back to my room later|Now I have to go"} },
    [A1_CORRIDOR_MAP_CHECK] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Tenemos la mejor colección|de mapas de @[todos los gremios@]",
         "We have the best collection|of maps from @[all guilds@]"} },
    [A1_CORRIDOR_REVISIT_MEMORIES] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Antes de irme quiero|repasar algunos recuerdos|Se lo debo a papá",
         "Before I leave I want to|revisit some memories|I owe it to dad"} },
    [A1_CORRIDOR_TERM_2] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_CORRIDOR_BOOK_HISTORY] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Este tomo narra la historia|de nuestro gremio|desde la @[Gran Separación@]",
         "This volume narrates the history|of our guild|since the @[Great Split@]"} },
    [A1_CORRIDOR_BOOK_HIST2] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Sequías, pactos, viajes,|fundaciones, incendios...",
         "Droughts, pacts, journeys,|foundings, fires..."} },
    [A1_CORRIDOR_BOOK_HIST3] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Cuando alguien lo escribe|después, todo parece|más ordenado",
         "When someone writes it|down later, it all seems|more orderly"} },
    [A1_CORRIDOR_BOOK_ENDS_WITH_FATHER] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"El último capítulo|termina con el fallecimiento|de mi padre",
         "The last chapter|ends with the passing|of my father"} },
    [A1_CORRIDOR_BOOK_MOTHER_WRITES_NEXT] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Madre dice que seré yo|quien deba escribir|la siguiente página",
         "Mother says it will be me|who must write|the next page"} },
    [A1_CORRIDOR_TERM_3] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_CORRIDOR_BOOK_AGAIN] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"La historia del gremio|Y una página aún en blanco",
         "The history of the guild|And a page still blank"} },
    [A1_CORRIDOR_TERM_4] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_CORRIDOR_MYTH_COLLECTION] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Una colección de|mitos y leyendas|de los distintos gremios",
         "A collection of|myths and legends|from the different guilds"} },
    [A1_CORRIDOR_MYTH2] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Pastores que cantan|Herreros que forjan|Cristaleros que ven el mañana",
         "Shepherds who sing|Blacksmiths who forge|Glassmakers who see tomorrow"} },
    [A1_CORRIDOR_MYTH3] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Se cuenta que faltan|algunos gremios|perdidos en el tiempo",
         "They say some guilds|are missing,|lost in time"} },
    [A1_CORRIDOR_MYTH_PASTORS] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Gracias a mi padre|tenemos documentadas|las que cantaban los @[Pastores@]",
         "Thanks to my father|we have documented|those the @[Shepherds@] sang"} },
    [A1_CORRIDOR_TERM_5] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_CORRIDOR_MYTH_AGAIN] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Mitos y leyendas|Y a veces verdades",
         "Myths and legends|And sometimes truths"} },
    [A1_CORRIDOR_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem act1_hall[] = {
    [A1_HALL_GUILD_YEAR] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"@[Gremio de los historiadores@]|Año 8121",
         "@[Historians guild@]|Year 8121"} },
    [A1_HALL_MONDAY_MORNING] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Lunes|Primera hora de la mañana",
         "Monday|Early morning"} },
    [A1_HALL_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HALL_CLIO_LATE] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Es tarde, Linus|Y uno no debe llegar tarde|a su cumpleaños",
         "It's late, Linus|And you shouldn't be late|at your birthday"} },
    [A1_HALL_LINUS_STRANGEST_DREAM] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"He tenido un sueño|de lo más extraño, Madre",
         "I have had the strangest|dream, Mother"} },
    [A1_HALL_SWAN_CAME] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Un @[cisne@] venía a|mi cuarto y...",
         "A @[swan@] came to my room|and..."} },
    [A1_HALL_CLIO_TELL_LATER] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Luego me lo cuentas|@[Xander@] nos espera",
         "You can tell me later|@[Xander@] is waiting for us"} },
    [A1_HALL_TERM_2] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HALL_XANDER_AWAKE] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Por fin|estás despierto, Linus",
         "At last,|you're awake Linus"} },
    [A1_HALL_LINUS_FORGIVE] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Perdóname, maestro|Un extraño sueño me ha|mantenido despierto",
         "Forgive me, master|A strange dream has|kept me awake"} },
    [A1_HALL_XANDER_YOUR_FATHERS_SON] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Ciertamente eres el|hijo de tu padre|@[Aiden@] tenía grandes sueños",
         "You are certainly your|father's son|@[Aiden@] had big dreams"} },
    [A1_HALL_XANDER_UNFULFILLED] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Y estamos aquí para hablar|sobre uno que|nunca llegó a cumplir",
         "And we are here to talk|about one that he|never achieved"} },
    [A1_HALL_LINUS_WHICH_STORY] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"He leído sus historias|mil veces|¿De cuál hablamos?",
         "I've read his stories|a thousand times|Which one is this?"} },
    [A1_HALL_XANDER_ISLAND_LEGEND] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Una que no encontrarás en|un libro. La de la isla|del @[Gremio de los Tejedores@]",
         "One you won't find in a book|The one about @[Weavers|guild@] island"} },
    [A1_HALL_TERM_3] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HALL_XANDER_ABILITY] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Según la leyenda|Fueron un gremio|capaz de tejer hechizos",
         "According to the legend|They were a guild|able to weave spells"} },
    [A1_HALL_XANDER_NOT_LEGEND] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Para él no era una leyenda|Los @[Pastores@] la cantaban|como cierta",
         "That was no legend for him|@[Shepherds@] sang it as a fact"} },
    [A1_HALL_XANDER_VANISHED] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Desaparecieron sin dejar rastro|Aunque muchos creen|que era solo un cuento",
         "They vanished without a trace|Although many believe|it was just a tale"} },
    [A1_HALL_XANDER_WEAVE] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Tejían la luz|El sonido|La forma misma de las cosas",
         "They wove light|Sound|The very shape of things"} },
    [A1_HALL_TERM_4] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HALL_ENCARGO] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Escúchame bien, Linus|Durante décadas este gremio|ha conservado la memoria",
         "Listen well, Linus|For decades this guild|has kept the world's memory"} },
    [A1_HALL_ENCARGO2] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Pero también ha decidido|qué recuerdos era|preferible no tocar",
         "But it has also decided|which memories were|better left untouched"} },
    [A1_HALL_ENCARGO3] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"¿Estás diciendo|que lo ocultasteis?",
         "Are you saying|you hid it?"} },
    [A1_HALL_ENCARGO4] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Los rumores debían|quedar como rumores|Pero ahora hay señales:",
         "Rumours had to stay|rumours|But now there are signs:"} },
    [A1_HALL_ENCARGO5] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Canciones recordadas|que nadie ha enseñado|Sueños repetidos",
         "Songs remembered|that no one has taught|Repeated dreams"} },
    [A1_HALL_ENCARGO6] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Yo también he tenido uno",
         "I've had one too"} },
    [A1_HALL_ENCARGO7] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"El @[cisne@] dijo que habían|pasado @[cien años@]|Y que no podrían detenerle",
         "The @[swan@] said a @[hundred|years@] had passed|And they couldn't hold him"} },
    [A1_HALL_ENCARGO8] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Entonces ya no hay tiempo|para fingir ignorancia|Iréis a la isla",
         "Then there's no more time|to feign ignorance|You will go to the island"} },
    [A1_HALL_ENCARGO9] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Observaréis lo que quede del|@[Gremio de los Tejedores@]|Y volveréis a contar su historia",
         "You'll see what remains of|the @[Weavers guild@]|And return to tell their story"} },
    [A1_HALL_ENCARGO10] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No tenemos mapa",
         "We have no map"} },
    [A1_HALL_ENCARGO11] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"@[Aiden@] dejó notas|Incompletas, pero suficientes",
         "@[Aiden@] left notes|Incomplete, but enough"} },
    [A1_HALL_CLIO_DESTINY] = { FACE_clio, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Nuestro destino es|documentar hechos,|no perseguirlos",
         "Our destiny is to|document facts,|not to chase them"} },
    [A1_HALL_XANDER_LINUS_AGE] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Linus tiene diecisiete años|Esa era mi edad cuando|viajé por el mundo",
         "Linus is seventeen|That was my age when|I traveled the world"} },
    [A1_HALL_XANDER_FATHERS_AGE] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Y la edad de su padre cuando|llegó aquí",
         "And his father's age when|he came to us"} },
    [A1_HALL_XANDER_BEFORE_JOINED] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Un año antes de que|le acogiéramos|como uno de los nuestros",
         "A year before we|took him as one of ours"} },
    [A1_HALL_LINUS_MOTHER] = { FACE_linus, SIDE_RIGHT, 100,
        {"Madre...",
         "Mother..."} },
    [A1_HALL_TERM_5] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HALL_CLIO_IF_XANDER_WANTS] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Si Xander lo quiere, así será|Pero no irás solo",
         "If Xander wants it that way,|so it will be|But you'll not go alone"} },
    [A1_HALL_CLIO_I_WONT_LET_YOU] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Nunca me ha gustado viajar|Pero no dejaré que vayas solo",
         "I've never liked to travel|But I won't let you go alone"} },
    [A1_HALL_TERM_6] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HALL_CLIO_PREPARE] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Prepararé lo necesario",
         "I'll prepare what we need"} },
    [A1_HALL_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem act1_forest[] = {
    [A1_FOREST_SOME_TIME_LATER] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Algún tiempo después",
         "Some time later"} },
    [A1_FOREST_ENEMIES_APPROACHING] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Se aproximan enemigos|Tenemos que estar atentos|Quédate cerca, madre",
         "Enemies are approaching|We have to stay alert|Stay close, mother"} },
    [A1_FOREST_NOTE_ABOUT_SCENE] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"@[NOTA@]: Puede que esta escena o estos|hechizos no estén en el|juego cuando esté terminado",
         "@[NOTE@]: This scene or these|spells may not be in the|game when finished"} },
    [A1_FOREST_DEMO_REASON] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Se ha decidido incluirla|en esta demo técnica|como prueba de ciertas mecánicas",
         "It's been decided to include it|in this technical demo|as a test of certain mechanics"} },
    [A1_FOREST_PRESS_START] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Pulsa @[START@] para ver|tu inventario de hechizos",
         "Press @[START@] to view|your spell inventory"} },
    [A1_FOREST_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_FOREST_3BUTTONS] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Vaya, parece que estás usando|@[un mando de tres botones@]",
         "Oops, it seems you are using|@[a three-button controller@]"} },
    [A1_FOREST_BUTTONS_HINT] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"El juego completo necesitará|@[seis botones@], pero para esta demo|solo necesitas tres",
         "The full game will need|@[six buttons@], but for this demo|you only need three"} },
    [A1_FOREST_TERM_2] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_FOREST_THAT_HURTS] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Eso ha dolido",
         "That hurts"} },
    [A1_FOREST_THINK_BACKWARDS] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Quizá deba pensar|al revés",
         "I should maybe|think backwards"} },
    [A1_FOREST_TRY_HIDE_OR_THUNDER] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Puedo probar a esconderme|o tratar de invocar|al trueno",
         "I could try to hide|or attempt to summon|the thunder"} },
    [A1_FOREST_REVERSE_HINT] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Tengo que contraatacar|justo después de su hechizo",
         "I have to counterattack|right after their spell"} },
    [A1_FOREST_REVERSE_NOTES_COUNTER] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Si reproduzco al revés|las notas, podré|contraatacar este hechizo",
         "If I play the notes backwards|I could be able to|counter the spell"} },
    [A1_FOREST_NO_EFFECT] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No parece afectarles",
         "It doesn't seem to affect them"} },
    [A1_FOREST_CANT_CAST_WHILE_HIDDEN] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No puedo lanzar hechizos|si estoy escondido",
         "I can't launch spells|while hiding"} },
    [A1_FOREST_GOOD_IDEA_HIDE] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Buena idea. Así no me verán",
         "Good idea. They won't see me"} },
    [A1_FOREST_THATS_ALL] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"@[¡Esto es todo!@]|(por ahora)",
         "@[That's all!@]|(by now)"} },
    [A1_FOREST_THANKS_FOR_PLAYING] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Gracias por probar la demo técnica|Síguenos por X o BlueSky|@[@GeeseBumpsGames@]",
         "Thanks for testing our tech demo|Follow us in X or BlueSky|@[@GeeseBumpsGames@]"} },
    [A1_FOREST_TURN_OFF_CONSOLE] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Apaga tu consola|y haz algo constructivo|como jugar un poco al frontón",
         "Turn off your console|and do something constructive|like play a little racquetball"} },
    [A1_FOREST_ORGANIZE_SOCKS] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"o preparar la cena,|o organizar tu cajón de calcetines|alfabéticamente.",
         "or cook dinner,|or organize your sock drawer|alphabetically."} },
    [A1_FOREST_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem act1_bedroom[] = {
    [A1_BEDROOM_HUNDRED_YEARS] = { FACE_swan, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Han pasado ya cien años",
         "A hundred years have passed"} },
    [A1_BEDROOM_SWAN2] = { FACE_swan, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Cien años desde que|cantamos para contenerle",
         "A hundred years since|we sang to contain him"} },
    [A1_BEDROOM_SWAN3] = { FACE_swan, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Pero @[el tejido@]|se está rompiendo",
         "But @[the weave@]|is breaking"} },
    [A1_BEDROOM_CANT_STOP_LONG] = { FACE_swan, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No podremos detenerle|mucho más tiempo",
         "We won't be able to|hold him much longer"} },
    [A1_BEDROOM_SWAN5] = { FACE_swan, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"@[Linus Wordweaver@]...",
         "@[Linus Wordweaver@]..."} },
    [A1_BEDROOM_SWAN6] = { FACE_swan, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Cuando despiertes,|escucha lo que ya sabías",
         "When you wake,|listen to what you already knew"} },
    [A1_BEDROOM_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_BEDROOM_NEXT_MORNING] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"A la mañana siguiente...",
         "The next morning..."} },
    [A1_BEDROOM_AWAKE] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Otra vez|El mismo sueño|con la misma voz",
         "Again|The same dream|with the same voice"} },
    [A1_BEDROOM_SLEPT_BAD] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"He dormido regular esta noche|Tuve horribles pesadillas",
         "I've not slept well last night|I had terrible nightmares"} },
    [A1_BEDROOM_NO_TIME_TO_SIT] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No tengo tiempo de sentarme|@[Madre@] me espera",
         "I don't have time to sit down|@[Mother@] is waiting for me"} },
    [A1_BEDROOM_NOT_REAL] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No ha podido ser real|La ventana está cerrada",
         "It couldn't be real|The windows is closed"} },
    [A1_BEDROOM_LULLABY] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Esta es la @[nana@] que me|cantaban cada noche",
         "That's the @[lullaby@] they used|to sing to me every night"} },
    [A1_BEDROOM_TERM_2] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_BEDROOM_LEARNED_PATTERN] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Has aprendido|tu primer @[patrón@]",
         "You have learned|your first @[pattern@]"} },
    [A1_BEDROOM_ENTER_PAUSE_MENU] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Entra en el menú de|pausa para verlo",
         "Enter the pause menu|to check it out"} },
    [A1_BEDROOM_TERM_3] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_BEDROOM_FOURNOTES] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Cuatro notas|Parecen poco relevantes|Pero importan mucho",
         "Four notes|They seem unimportant|But they matter a lot"} },
    [A1_BEDROOM_TERM_4] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_BEDROOM_MOTHER_CALLS] = { FACE_clio, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"@[Linus@], ¿dónde estás?",
         "@[Linus@], where are you?"} },
    [A1_BEDROOM_TOO_LATE] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Se me ha hecho demasiado tarde|tengo que ir al salón",
         "It's gotten too late|I need to go the hall"} },
    [A1_BEDROOM_PORTRAIT] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Padre, madre y yo",
         "Father, Mother and me"} },
    [A1_BEDROOM_PORTRAIT2] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Es extraño cómo una imagen|puede parecer más viva|que una habitación entera",
         "It's strange how a picture|can seem more alive|than a whole room"} },
    [A1_BEDROOM_PORTRAIT3] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Parece que fue ayer|cuando @[Padre@] estaba|con nosotros",
         "It seems like yesterday|when @[Father@] was|with us"} },
    [A1_BEDROOM_TERM_5] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_BEDROOM_TERM_6] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_BEDROOM_CHEST] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Juguetes viejos:|cuerdas, tablillas,|una flauta rota...",
         "Old toys:|strings, small boards,|a broken flute..."} },
    [A1_BEDROOM_CHEST2] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Padre insistía en que|aprendiera música aunque|no fuera pastor",
         "Father insisted I learn|music even if I was|no shepherd"} },
    [A1_BEDROOM_TERM_7] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_BEDROOM_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem act1_test[] = {
    [A1_TEST_INTRO] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Banco de pruebas|del motor de escenas",
         "TEST: Scene engine|test bench"} },
    [A1_TEST_INTRO_2] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Un menú permite probar|cada sección y volver|Botones: A=MI B=FA C=SOL|X=LA Y=SI Z=DO",
         "A menu lets you test|each section and return|Buttons: A=MI B=FA C=SOL|X=LA Y=SI Z=DO"} },
    [A1_TEST_INTRO_3] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Pulsa @[A@] para empezar",
         "Press @[A@] to start"} },
    [A1_TEST_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_TEST_HUB] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: ¿Qué sección|quieres probar?",
         "TEST: Which section|do you want to test?"} },
    [A1_TEST_DLG_CLIO] = { FACE_clio, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"TEST: Cara de Clio|a la derecha",
         "TEST: Clio face|on the right"} },
    [A1_TEST_DLG_XANDER] = { FACE_xander, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Cara de Xander|a la izquierda",
         "TEST: Xander face|on the left"} },
    [A1_TEST_ANIM] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Animación de magia|lanzada por opcode del DSL",
         "TEST: Magic animation|via DSL opcode"} },
    [A1_TEST_QUIZ_Q1] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST Quiz 1 de 2:|¿Cuántas notas tiene un|patrón del jugador?",
         "TEST Quiz 1 of 2:|How many notes has|a player pattern?"} },
    [A1_TEST_QUIZ_BAD] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Respuesta incorrecta|Inténtalo otra vez",
         "TEST: Wrong answer|Try again"} },
    [A1_TEST_QUIZ_Q2] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST Quiz 2 de 2:|¿Qué hechizo es palíndromo|y no puede invertirse?",
         "TEST Quiz 2 of 2:|Which spell is a palindrome|and cannot be reversed?"} },
    [A1_TEST_QUIZ_CONF] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: ¿Estás seguro|de tu respuesta?",
         "TEST: Are you sure|about your answer?"} },
    [A1_TEST_QUIZ_OK] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: ¡Quiz superado!|Choices anidados y|reintentos funcionan",
         "TEST: Quiz passed!|Nested choices and|retries work"} },
    [A1_TEST_DEMO_CAST] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Cast scripted de @[sleep@]|(solo posible por guion)",
         "TEST: Scripted @[sleep@] cast|(script-only spell)"} },
    [A1_TEST_LIGHT_DEMO] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Cast scripted de @[luz@]|hechizo nuevo hecho con|fases declarativas",
         "TEST: Scripted @[light@] cast|new spell built from|declarative phases"} },
    [A1_TEST_PUZ_CHOICE] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: ¿Qué puzzle|quieres probar?",
         "TEST: Which puzzle|do you want to try?"} },
    [A1_TEST_PUZZLE_INTRO] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST Puzzle 1: lanza|@[trueno@], @[fuego@] y @[esconderse@]|en ese orden",
         "TEST Puzzle 1: cast|@[thunder@], @[fire@] and @[hide@]|in that order"} },
    [A1_TEST_PUZZLE_INTRO_2] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Notas: trueno MI FA SOL SOL|fuego MI FA SOL LA|esconderse FA SOL SOL FA",
         "Notes: thunder MI FA SOL SOL|fire MI FA SOL LA|hide FA SOL SOL FA"} },
    [A1_TEST_PUZZLE_INTRO_3] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Fallar un hechizo reinicia|la secuencia desde cero",
         "A wrong cast restarts|the sequence from zero"} },
    [A1_TEST_TERM_2] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_TEST_PUZ2_INTRO] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST Puzzle 2: con INVERTIDO|@[trueno@], @[luz invertida@]|y @[esconderse@]",
         "TEST Puzzle 2: with REVERSED|@[thunder@], @[reversed light@]|and @[hide@]"} },
    [A1_TEST_PUZ2_INTRO_2] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Notas: trueno MI FA SOL SOL|luz invertida DO SI LA SOL|esconderse FA SOL SOL FA",
         "Notes: thunder MI FA SOL SOL|reversed light DO SI LA SOL|hide FA SOL SOL FA"} },
    [A1_TEST_TERM_3] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_TEST_NEVER] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: ERROR|esto no debería verse",
         "TEST: ERROR|you should never see this"} },
    [A1_TEST_PUZZLE_OK] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: ¡Secuencia correcta!|La puerta se abre",
         "TEST: Correct sequence!|The door opens"} },
    [A1_TEST_COMBAT] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST Oleada 1: fantasma|clásico. Contrarresta su|trueno con SOL SOL FA MI",
         "TEST Wave 1: classic ghost|Counter its thunder|with SOL SOL FA MI"} },
    [A1_TEST_WAVE2] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST Oleada 2: fantasma con|DOS hechizos. El @[mordisco@]|NO se puede contrarrestar",
         "TEST Wave 2: ghost with|TWO spells. The @[bite@]|cannot be countered"} },
    [A1_TEST_VICTORY] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Combate superado|Volviendo al menú",
         "TEST: Combat cleared|Back to the menu"} },
    [A1_TEST_COMBAT_MENU] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: ¿Qué tipo|de combate?",
         "TEST: Which kind|of combat?"} },
    [A1_TEST_MELEE] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST Jabalíes: sin vara.|Pulsa @[A@] para golpear|Seis golpes los ahuyentan",
         "TEST Boars: no rod.|Press @[A@] to strike|Six hits drive them away"} },
    [A1_TEST_DEFEAT] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Te han derrotado|Reintentando el combate",
         "TEST: You were defeated|Retrying the combat"} },
    [A1_TEST_BYE] = { FACE_linus, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"TEST: Fin del banco de pruebas|Volviendo al dormitorio",
         "TEST: End of the test bench|Returning to the bedroom"} },
    [A1_TEST_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem act1_coast[] = {
    [A1_COAST_ARRIVE] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"@[Isla desconocida@]|Un mes más tarde",
         "@[Unknown island@]|One month later"} },
    [A1_COAST_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_COAST_L1] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Por fin llegamos, @[Madre@]",
         "We finally made it, @[Mother@]"} },
    [A1_COAST_L1b] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Así que existía",
         "So it did exist"} },
    [A1_COAST_L1c] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"¿Dónde llevará el camino?",
         "Where does the path lead?"} },
    [A1_COAST_L1d] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Está a punto de anochecer|Tendremos que|averiguarlo rápido",
         "Night is almost here|We'll have to find out|quickly"} },
    [A1_COAST_TERM_2] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_COAST_TREE] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"@[Padre@] describía este árbol|exactamente así",
         "@[Father@] described this tree|exactly like this"} },
    [A1_COAST_TERM_3] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_COAST_ONWARD] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Todo parece quieto",
         "Everything seems still"} },
    [A1_COAST_ONWARDb] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Demasiado quieto",
         "Too still"} },
    [A1_COAST_TERM_4] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_COAST_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem act1_island[] = {
    [A1_ISLAND_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_ISLAND_COMBAT] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"¡@[Madre@], detrás!",
         "@[Mother@], behind you!"} },
    [A1_ISLAND_COMBATb] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Pulsa @[A@] para actuar",
         "Press @[A@] to act"} },
    [A1_ISLAND_COMBATc] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"A lo mejor les|asusta el fuego",
         "Maybe the fire|will scare them"} },
    [A1_ISLAND_TERM_2] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_ISLAND_HURT] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"¡@[Madre@]!|Estás herida",
         "@[Mother@]!|You're hurt"} },
    [A1_ISLAND_HURTb] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No es grave",
         "It's not serious"} },
    [A1_ISLAND_HURTc] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No sé si podré|continuar, hijo",
         "I don't know if I can|go on, son"} },
    [A1_ISLAND_HURTd] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"@[Madre@], no puedes|dejarme solo",
         "@[Mother@], you can't|leave me alone"} },
    [A1_ISLAND_HURTe] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Sé que @[Padre@]|te enseñó sus canciones",
         "I know @[Father@]|taught you his songs"} },
    [A1_ISLAND_HURTf] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Linus...",
         "Linus..."} },
    [A1_ISLAND_HURTg] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"No me puedes dejar",
         "You can't leave me"} },
    [A1_ISLAND_TERM_3] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_ISLAND_HEALED] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Ya estoy mejor|Puedo seguir",
         "I'm better now|I can go on"} },
    [A1_ISLAND_HEALEDb] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Así que era verdad",
         "So it was true"} },
    [A1_ISLAND_HEALEDc] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Nunca dije|que fuera mentira",
         "I never said|it was a lie"} },
    [A1_ISLAND_HEALEDd] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Has reconocido el patrón|de @[Curación@]",
         "You have recognised the|@[Healing@] pattern"} },
    [A1_ISLAND_HEALEDe] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Prométeme que no|se lo contarás a @[Xander@]",
         "Promise me you won't|tell @[Xander@]"} },
    [A1_ISLAND_TERM_4] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_ISLAND_ONWARD] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"@[Madre@]|Allí|Una choza",
         "@[Mother@]|Over there|A hut"} },
    [A1_ISLAND_ONWARDb] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"O lo que queda de ella",
         "Or what's left of it"} },
    [A1_ISLAND_TERM_5] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_ISLAND_DEFEAT] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"¡En pie, Linus!|Vuelven a por nosotros",
         "On your feet, Linus!|They're coming back"} },
    [A1_ISLAND_TERM_6] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_ISLAND_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem act1_hut[] = {
    [A1_HUT_ENTER] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Mira esos marcos",
         "Look at those frames"} },
    [A1_HUT_ENTERb] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"No son telares como los|de un artesano normal",
         "They're not looms like|a common craftsman's"} },
    [A1_HUT_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HUT_LOOM] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"@[Madre@]...|¿Será este el hogar|de los @[Tejedores@]?",
         "@[Mother@]...|Could this be the home|of the @[Weavers@]?"} },
    [A1_HUT_LOOMb] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"En algún momento lo fue",
         "At some point it was"} },
    [A1_HUT_LOOMc] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Se hace de noche|El camino de vuelta|será peligroso",
         "Night is falling|The way back|will be dangerous"} },
    [A1_HUT_TERM_2] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HUT_DEBRIS] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Bastidores rotos",
         "Broken frames"} },
    [A1_HUT_DEBRISb] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Y símbolos que el gremio|jamás copió en sus libros",
         "And symbols the guild|never copied in its books"} },
    [A1_HUT_TERM_3] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HUT_THREADS] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Hilos quemados,|aún tibios",
         "Burnt threads,|still warm"} },
    [A1_HUT_TERM_4] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HUT_STAFF] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"¿Qué es eso?",
         "What is that?"} },
    [A1_HUT_STAFFb] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No lo toques",
         "Don't touch it"} },
    [A1_HUT_STAFFc] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"No parece madera normal|Está vibrando",
         "It doesn't look like|ordinary wood|It's vibrating"} },
    [A1_HUT_TERM_5] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HUT_SYSTEM] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Has obtenido el @[bastón@]",
         "You have obtained|the @[staff@]"} },
    [A1_HUT_SYSTEMb] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Patrón inscrito:|@[Electricidad@]",
         "Pattern inscribed:|@[Lightning@]"} },
    [A1_HUT_SYSTEMc] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Ya puedes lanzar magia",
         "You can now cast magic"} },
    [A1_HUT_TERM_6] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HUT_AWED] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"@[Madre@]...|Lo he oído",
         "@[Mother@]...|I heard it"} },
    [A1_HUT_AWEDb] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"No con mis oídos",
         "Not with my ears"} },
    [A1_HUT_TERM_7] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HUT_BOBBIN] = { FACE_swan, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"El tejido se está rompiendo|No aguantará mucho más",
         "The weave is breaking|It won't hold much longer"} },
    [A1_HUT_BOBBINb] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"¿Has oído eso?|Era él",
         "Did you hear that?|It was him"} },
    [A1_HUT_BOBBINc] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"¿El @[cisne@]?",
         "The @[swan@]?"} },
    [A1_HUT_BOBBINd] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Sí",
         "Yes"} },
    [A1_HUT_TERM_8] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HUT_LEAVE] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Tenemos que volver ahora",
         "We must go back now"} },
    [A1_HUT_LEAVEb] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Es muy tarde|y va a llegar la @[tormenta@]",
         "It's very late|and the @[storm@] is coming"} },
    [A1_HUT_TERM_9] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HUT_SHADOW] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"¿Has visto eso?|Algo se ha movido|entre los restos",
         "Did you see that?|Something moved|among the remains"} },
    [A1_HUT_TERM_10] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_HUT_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem act1_return[] = {
    [A1_RETURN_START] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Camina|No mires atrás",
         "Keep walking|Don't look back"} },
    [A1_RETURN_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_RETURN_BOARS] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Otra vez|Y ahora no tengo fuego",
         "Again|And now I have no fire"} },
    [A1_RETURN_TERM_2] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_RETURN_BOARS_WON] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Han retrocedido",
         "They've fallen back"} },
    [A1_RETURN_BOARS_WONb] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Volverán|No podemos perder tiempo",
         "They'll return|We can't waste time"} },
    [A1_RETURN_TERM_3] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_RETURN_BOBBIN_HINT] = { FACE_swan, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Canta el patrón|de los cielos",
         "Sing the pattern|of the skies"} },
    [A1_RETURN_TERM_4] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_RETURN_GHOSTS] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"¿Qué son esas cosas?",
         "What are those things?"} },
    [A1_RETURN_GHOSTSb] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No sé si queremos saberlo",
         "I'm not sure we want to know"} },
    [A1_RETURN_TERM_5] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_RETURN_DEFEAT] = { FACE_swan, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"La solución es a veces|lo contrario del problema",
         "The answer is sometimes|the opposite of the problem"} },
    [A1_RETURN_TERM_6] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_RETURN_GHOSTS_WON] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Se han ido",
         "They're gone"} },
    [A1_RETURN_GHOSTS_WONb] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No|Se han retirado",
         "No|They've withdrawn"} },
    [A1_RETURN_TERM_7] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_RETURN_DONE] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Ahí está la nave",
         "There's the ship"} },
    [A1_RETURN_DONEb] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"No aflojes aún",
         "Don't slow down yet"} },
    [A1_RETURN_TERM_8] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_RETURN_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem act1_coast_end[] = {
    [A1_END_DIALOG] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"Los @[Tejedores@]...|Todo era verdad",
         "The @[Weavers@]...|It was all true"} },
    [A1_END_DIALOGb] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Salgamos cuanto antes|de esta isla",
         "Let's leave this island|as soon as we can"} },
    [A1_END_DIALOGc] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"En este @[bastón@]|resuena la magia",
         "Magic resonates|in this @[staff@]"} },
    [A1_END_DIALOGd] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"La magia era peligrosa|Desapareció de los libros|hace muchos años",
         "Magic was dangerous|It vanished from books|many years ago"} },
    [A1_END_DIALOGe] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"No desapareció|La borrasteis",
         "It didn't vanish|You erased it"} },
    [A1_END_DIALOGf] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"La escondimos|No es lo mismo",
         "We hid it|That's not the same"} },
    [A1_END_DIALOGg] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Lo hicimos para que el mundo|no volviera a romperse",
         "We did it so the world|would not break again"} },
    [A1_END_DIALOGh] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"@[Padre@] sabía más|de lo que nos contó|Y tú también",
         "@[Father@] knew more|than he told us|And so do you"} },
    [A1_END_DIALOGi] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Lo suficiente",
         "Enough"} },
    [A1_END_DIALOGj] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"¿Qué hacemos ahora?",
         "What do we do now?"} },
    [A1_END_DIALOGk] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Reabrir viejas historias",
         "Reopen old stories"} },
    [A1_END_DIALOGl] = { FACE_linus, SIDE_RIGHT, DEFAULT_TALK_TIME,
        {"¿Adónde iremos?",
         "Where will we go?"} },
    [A1_END_DIALOGm] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Al @[Gremio de los Pastores@]",
         "To the @[Shepherds guild@]"} },
    [A1_END_DIALOGn] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Allí empezó|la sangre de tu padre",
         "That's where your father's|blood began"} },
    [A1_END_DIALOGo] = { FACE_clio, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Y quizá allí encontremos|la parte de la canción|que nos falta",
         "And maybe there we'll find|the part of the song|we're missing"} },
    [A1_END_TERM_1] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_END_PAUSE] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Mira la isla|por última vez|Pulsa @[A@] para embarcar",
         "Look at the island|one last time|Press @[A@] to board"} },
    [A1_END_TERM_2] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_END_BOBBIN] = { FACE_swan, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Tranquilo, Linus",
         "Be at ease, Linus"} },
    [A1_END_BOBBINb] = { FACE_swan, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"Nunca estarás solo",
         "You will never be alone"} },
    [A1_END_TERM_3] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_END_FIN] = { FACE_none, SIDE_LEFT, DEFAULT_TALK_TIME,
        {"@[FIN DEL ACTO 1@]",
         "@[END OF ACT 1@]"} },
    [A1_END_TERM_4] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } },
    [A1_END_COUNT] = { 0, false, DEFAULT_TALK_TIME, { NULL, NULL } }
};

const DialogItem *dialogs[] = {
    system_dialog,  // 0
    act1_corridor,  // 1
    act1_hall,  // 2
    act1_forest,  // 3
    act1_bedroom,  // 4
    act1_test,  // 5
    act1_coast,  // 6
    act1_island,  // 7
    act1_hut,  // 8
    act1_return,  // 9
    act1_coast_end,  // 10
};
