// Auto-generated from texts.csv and clusters.csv – DO NOT EDIT
#ifndef _TEXTS_DATA_H_
#define _TEXTS_DATA_H_

#include "narrative/texts.h"

enum SystemDialogId {
    SYSMSG_DEMO_TITLE = 0,
    SYSMSG_DISCLAIMER = 1,
    SYSMSG_TERM_1 = 2,
    SYSMSG_CANT_USE_PATTERN = 3,
    SYSMSG_COUNT = 4
};

enum Act1CorridorId {
    A1_CORRIDOR_OVERSLEPT = 0,
    A1_CORRIDOR_MEMORIES = 1,
    A1_CORRIDOR_TERM_1 = 2,
    A1_CORRIDOR_DOOR1_CHECK = 3,
    A1_CORRIDOR_DOOR2_CHECK = 4,
    A1_CORRIDOR_DOOR3_CHECK = 5,
    A1_CORRIDOR_MAP_CHECK = 6,
    A1_CORRIDOR_REVISIT_MEMORIES = 7,
    A1_CORRIDOR_TERM_2 = 8,
    A1_CORRIDOR_BOOK_HISTORY = 9,
    A1_CORRIDOR_BOOK_ENDS_WITH_FATHER = 10,
    A1_CORRIDOR_BOOK_MOTHER_WRITES_NEXT = 11,
    A1_CORRIDOR_TERM_3 = 12,
    A1_CORRIDOR_MYTH_COLLECTION = 13,
    A1_CORRIDOR_MYTH_PASTORS = 14,
    A1_CORRIDOR_COUNT = 15
};

enum Act1HallId {
    A1_HALL_GUILD_YEAR = 0,
    A1_HALL_MONDAY_MORNING = 1,
    A1_HALL_TERM_1 = 2,
    A1_HALL_CLIO_LATE = 3,
    A1_HALL_LINUS_STRANGEST_DREAM = 4,
    A1_HALL_SWAN_CAME = 5,
    A1_HALL_CLIO_TELL_LATER = 6,
    A1_HALL_TERM_2 = 7,
    A1_HALL_XANDER_AWAKE = 8,
    A1_HALL_LINUS_FORGIVE = 9,
    A1_HALL_XANDER_YOUR_FATHERS_SON = 10,
    A1_HALL_XANDER_UNFULFILLED = 11,
    A1_HALL_LINUS_WHICH_STORY = 12,
    A1_HALL_XANDER_ISLAND_LEGEND = 13,
    A1_HALL_TERM_3 = 14,
    A1_HALL_XANDER_ABILITY = 15,
    A1_HALL_XANDER_NOT_LEGEND = 16,
    A1_HALL_XANDER_VANISHED = 17,
    A1_HALL_TERM_4 = 18,
    A1_HALL_XANDER_FATHER_WANTED = 19,
    A1_HALL_CLIO_DESTINY = 20,
    A1_HALL_XANDER_LINUS_AGE = 21,
    A1_HALL_XANDER_FATHERS_AGE = 22,
    A1_HALL_XANDER_BEFORE_JOINED = 23,
    A1_HALL_LINUS_MOTHER = 24,
    A1_HALL_TERM_5 = 25,
    A1_HALL_CLIO_IF_XANDER_WANTS = 26,
    A1_HALL_CLIO_I_WONT_LET_YOU = 27,
    A1_HALL_COUNT = 28
};

enum Act1ForestId {
    A1_FOREST_SOME_TIME_LATER = 0,
    A1_FOREST_ENEMIES_APPROACHING = 1,
    A1_FOREST_NOTE_ABOUT_SCENE = 2,
    A1_FOREST_DEMO_REASON = 3,
    A1_FOREST_PRESS_START = 4,
    A1_FOREST_TERM_1 = 5,
    A1_FOREST_3BUTTONS = 6,
    A1_FOREST_BUTTONS_HINT = 7,
    A1_FOREST_TERM_2 = 8,
    A1_FOREST_THAT_HURTS = 9,
    A1_FOREST_THINK_BACKWARDS = 10,
    A1_FOREST_TRY_HIDE_OR_THUNDER = 11,
    A1_FOREST_REVERSE_HINT = 12,
    A1_FOREST_REVERSE_NOTES_COUNTER = 13,
    A1_FOREST_CANT_CAST_WHILE_HIDDEN = 14,
    A1_FOREST_GOOD_IDEA_HIDE = 15,
    A1_FOREST_THATS_ALL = 16,
    A1_FOREST_THANKS_FOR_PLAYING = 17,
    A1_FOREST_TURN_OFF_CONSOLE = 18,
    A1_FOREST_ORGANIZE_SOCKS = 19,
    A1_FOREST_COUNT = 20
};

enum Act1BedroomId {
    A1_BEDROOM_HUNDRED_YEARS = 0,
    A1_BEDROOM_CANT_STOP_LONG = 1,
    A1_BEDROOM_TERM_1 = 2,
    A1_BEDROOM_NEXT_MORNING = 3,
    A1_BEDROOM_SLEPT_BAD = 4,
    A1_BEDROOM_NO_TIME_TO_SIT = 5,
    A1_BEDROOM_NOT_REAL = 6,
    A1_BEDROOM_LULLABY = 7,
    A1_BEDROOM_TERM_2 = 8,
    A1_BEDROOM_LEARNED_PATTERN = 9,
    A1_BEDROOM_ENTER_PAUSE_MENU = 10,
    A1_BEDROOM_TERM_3 = 11,
    A1_BEDROOM_MOTHER_CALLS = 12,
    A1_BEDROOM_TOO_LATE = 13,
    A1_BEDROOM_COUNT = 14
};

enum Act1TestId {
    A1_TEST_INTRO = 0,
    A1_TEST_INTRO_2 = 1,
    A1_TEST_INTRO_3 = 2,
    A1_TEST_INTRO_4 = 3,
    A1_TEST_INTRO_5 = 4,
    A1_TEST_INTRO_6 = 5,
    A1_TEST_TERM_1 = 6,
    A1_TEST_DEMO_CAST = 7,
    A1_TEST_CHOICE_R = 8,
    A1_TEST_CHOICE_R2 = 9,
    A1_TEST_PUZZLE_INTRO = 10,
    A1_TEST_PUZZLE_INTRO_2 = 11,
    A1_TEST_TERM_2 = 12,
    A1_TEST_NEVER = 13,
    A1_TEST_PUZZLE_OK = 14,
    A1_TEST_WALK = 15,
    A1_TEST_COMBAT = 16,
    A1_TEST_VICTORY = 17,
    A1_TEST_COUNT = 18
};

enum DialogSetId {
    SYSTEM_DIALOG,  // 0
    ACT1_CORRIDOR,  // 1
    ACT1_HALL,  // 2
    ACT1_FOREST,  // 3
    ACT1_BEDROOM,  // 4
    ACT1_TEST,  // 5
    DIALOG_SET_COUNT
};

#endif // _TEXTS_DATA_H_
