// Generated by tools/gen_scenes.py from data/scenes/*.scene — DO NOT EDIT
#include <genesis.h>
#include "core/core.h"  // SCREEN_WIDTH y otras constantes usadas en las tablas de setup
#include "scenes/scenes.h"
#include "narrative/narrative.h"
#include "actors/actors.h"
#include "spells/spells.h"
#include "world/world.h"
#include "res_all.h"      // recursos rescomp (tilesets, sprites, paletas) para las tablas de setup

static const SceneStep act1_bedroom_steps[] = {
    { SCENE_OP_LEVEL, 0, 0, 0, 0 }, // 0
    { SCENE_OP_LIMITS, 20, 145, 278, 176 }, // 1
    { SCENE_OP_PALETTE, PAL1, 0, 0, 0 }, // 2
    { SCENE_OP_CHARACTER, CHR_swan, 0, 0, 0 }, // 3
    { SCENE_OP_CHARACTER, CHR_linus, 0, 0, 0 }, // 4
    { SCENE_OP_ITEM, 0, 0, 0, 0 }, // 5
    { SCENE_OP_ITEM, 1, 1, 0, 0 }, // 6
    { SCENE_OP_ITEM, 2, 2, 0, 0 }, // 7
    { SCENE_OP_ITEM, 3, 3, 0, 0 }, // 8
    { SCENE_OP_ITEM, 4, 4, 0, 0 }, // 9
    { SCENE_OP_ITEM, 5, 5, 0, 0 }, // 10
    { SCENE_OP_ITEM, 7, 6, 0, 0 }, // 11
    { SCENE_OP_CALL, HOOK_ACT1_BEDROOM_SWAN, 0, 0, 0 }, // 12
    { SCENE_OP_CALL, HOOK_ACT1_BEDROOM_WAKE, 0, 0, 0 }, // 13
    { SCENE_OP_CALL, HOOK_ACT1_BEDROOM_ITEMS, 0, 0, 0 }, // 14
    { SCENE_OP_SAY, ACT1_BEDROOM, A1_BEDROOM_MOTHER_CALLS, 1, 0 }, // 15
    { SCENE_OP_SAY, ACT1_BEDROOM, A1_BEDROOM_TOO_LATE, 0, 0 }, // 16
    { SCENE_OP_NEXT_SCENE, SCENE_ACT1_CORRIDOR, 0, 0, 0 }, // 17
};

static const SceneStep act1_coast_steps[] = {
    { SCENE_OP_LEVEL, 1, 0, 0, 0 }, // 0
    { SCENE_OP_LIMITS, 0, 134, 275, 172 }, // 1
    { SCENE_OP_ITEM, 0, 7, 0, 0 }, // 2
    { SCENE_OP_ITEM, 1, 8, 0, 0 }, // 3
    { SCENE_OP_SET, SCENE_FLAG_ROD, 0, 0, 0 }, // 4
    { SCENE_OP_CHARACTER, CHR_linus, 0, 0, 0 }, // 5
    { SCENE_OP_CHARACTER, CHR_clio, 0, 0, 0 }, // 6
    { SCENE_OP_ACTIVE, CHR_linus, 0, 0, 0 }, // 7
    { SCENE_OP_MOVE_INSTANT, CHR_linus, -30, 160, 0 }, // 8
    { SCENE_OP_MOVE_INSTANT, CHR_clio, -60, 160, 0 }, // 9
    { SCENE_OP_FOLLOW, CHR_clio, 1, 0, 0 }, // 10
    { SCENE_OP_SHOW, CHR_linus, 1, 0, 0 }, // 11
    { SCENE_OP_SHOW, CHR_clio, 1, 0, 0 }, // 12
    { SCENE_OP_SAY, ACT1_COAST, A1_COAST_ARRIVE, 1, 0 }, // 13
    { SCENE_OP_CALL, HOOK_ACT1_COAST_ARRIVE, 0, 0, 0 }, // 14
    { SCENE_OP_MOVE, CHR_linus, 60, 160, 0 }, // 15
    { SCENE_OP_SAY_CLUSTER, ACT1_COAST, A1_COAST_L1, 1, 0 }, // 16
    { SCENE_OP_SET, SCENE_FLAG_MOVEMENT, 1, 0, 0 }, // 17
    { SCENE_OP_SET, SCENE_FLAG_SCROLL, 1, 0, 0 }, // 18
    { SCENE_OP_CALL, HOOK_ACT1_COAST_EXPLORE, 0, 0, 0 }, // 19
    { SCENE_OP_SAY_CLUSTER, ACT1_COAST, A1_COAST_ONWARD, 1, 0 }, // 20
    { SCENE_OP_NEXT_SCENE, SCENE_ACT1_ISLAND, 0, 0, 0 }, // 21
};

static const SceneStep act1_coast_end_steps[] = {
    { SCENE_OP_LEVEL, 2, 0, 0, 0 }, // 0
    { SCENE_OP_LIMITS, 0, 134, 275, 172 }, // 1
    { SCENE_OP_SET, SCENE_FLAG_ROD, 1, 0, 0 }, // 2
    { SCENE_OP_CHARACTER, CHR_linus, 0, 0, 0 }, // 3
    { SCENE_OP_CHARACTER, CHR_clio, 0, 0, 0 }, // 4
    { SCENE_OP_ACTIVE, CHR_linus, 0, 0, 0 }, // 5
    { SCENE_OP_MOVE_INSTANT, CHR_linus, 340, 160, 0 }, // 6
    { SCENE_OP_MOVE_INSTANT, CHR_clio, 370, 160, 0 }, // 7
    { SCENE_OP_SHOW, CHR_linus, 1, 0, 0 }, // 8
    { SCENE_OP_SHOW, CHR_clio, 1, 0, 0 }, // 9
    { SCENE_OP_LOOK, CHR_linus, 1, 0, 0 }, // 10
    { SCENE_OP_LOOK, CHR_clio, 1, 0, 0 }, // 11
    { SCENE_OP_CALL, HOOK_ACT1_COAST_END_AMBIENT, 0, 0, 0 }, // 12
    { SCENE_OP_MOVE, CHR_linus, 210, 160, 0 }, // 13
    { SCENE_OP_MOVE, CHR_clio, 250, 160, 0 }, // 14
    { SCENE_OP_SAY_CLUSTER, ACT1_COAST_END, A1_END_DIALOG, 1, 0 }, // 15
    { SCENE_OP_SAY, ACT1_COAST_END, A1_END_PAUSE, 0, 0 }, // 16
    { SCENE_OP_SET, SCENE_FLAG_MOVEMENT, 1, 0, 0 }, // 17
    { SCENE_OP_WAIT_PRESS, 0, 0, 0, 0 }, // 18
    { SCENE_OP_SET, SCENE_FLAG_MOVEMENT, 0, 0, 0 }, // 19
    { SCENE_OP_MOVE, CHR_clio, 120, 152, 0 }, // 20
    { SCENE_OP_MOVE, CHR_linus, 90, 144, 0 }, // 21
    { SCENE_OP_CALL, HOOK_ACT1_END_EPILOGUE, 0, 0, 0 }, // 22
    { SCENE_OP_HARD_RESET, 0, 0, 0, 0 }, // 23
};

static const SceneStep act1_corridor_steps[] = {
    { SCENE_OP_LEVEL, 3, 0, 0, 0 }, // 0
    { SCENE_OP_LIMITS, 0, 140, 275, 168 }, // 1
    { SCENE_OP_ITEM, 0, 9, 0, 0 }, // 2
    { SCENE_OP_ITEM, 1, 10, 0, 0 }, // 3
    { SCENE_OP_ITEM, 2, 11, 0, 0 }, // 4
    { SCENE_OP_ITEM, 3, 12, 0, 0 }, // 5
    { SCENE_OP_ITEM, 4, 13, 0, 0 }, // 6
    { SCENE_OP_ITEM, 5, 14, 0, 0 }, // 7
    { SCENE_OP_ITEM, 6, 15, 0, 0 }, // 8
    { SCENE_OP_ITEM, 7, 16, 0, 0 }, // 9
    { SCENE_OP_ITEM, 8, 17, 0, 0 }, // 10
    { SCENE_OP_ITEM, 9, 18, 0, 0 }, // 11
    { SCENE_OP_ITEM, 10, 19, 0, 0 }, // 12
    { SCENE_OP_ITEM, 11, 20, 0, 0 }, // 13
    { SCENE_OP_CHARACTER, CHR_linus, 0, 0, 0 }, // 14
    { SCENE_OP_SAY_CLUSTER, SYSTEM_DIALOG, SYSMSG_DEMO_TITLE, 1, 0 }, // 15
    { SCENE_OP_MOVE_INSTANT, CHR_linus, 232, 154, 0 }, // 16
    { SCENE_OP_SHOW, CHR_linus, 1, 0, 0 }, // 17
    { SCENE_OP_SAY_CLUSTER, ACT1_CORRIDOR, A1_CORRIDOR_OVERSLEPT, 0, 0 }, // 18
    { SCENE_OP_SET, SCENE_FLAG_SCROLL, 1, 0, 0 }, // 19
    { SCENE_OP_SET, SCENE_FLAG_MOVEMENT, 1, 0, 0 }, // 20
    { SCENE_OP_CALL, HOOK_ACT1_CORRIDOR_ITEMS, 0, 0, 0 }, // 21
    { SCENE_OP_NEXT_SCENE, SCENE_ACT1_HALL, 0, 0, 0 }, // 22
};

static const SceneStep act1_forest_steps[] = {
    { SCENE_OP_LEVEL, 4, 0, 0, 0 }, // 0
    { SCENE_OP_LIMITS, 0, 134, 275, 172 }, // 1
    { SCENE_OP_ITEM, 0, 21, 0, 0 }, // 2
    { SCENE_OP_ITEM, 1, 22, 0, 0 }, // 3
    { SCENE_OP_ITEM, 2, 23, 0, 0 }, // 4
    { SCENE_OP_ITEM, 3, 24, 0, 0 }, // 5
    { SCENE_OP_ITEM, 4, 25, 0, 0 }, // 6
    { SCENE_OP_ITEM, 5, 26, 0, 0 }, // 7
    { SCENE_OP_ITEM, 6, 27, 0, 0 }, // 8
    { SCENE_OP_SET, SCENE_FLAG_ROD, 1, 0, 0 }, // 9
    { SCENE_OP_CHARACTER, CHR_linus, 0, 0, 0 }, // 10
    { SCENE_OP_CHARACTER, CHR_clio, 0, 0, 0 }, // 11
    { SCENE_OP_ACTIVE, CHR_linus, 0, 0, 0 }, // 12
    { SCENE_OP_MOVE_INSTANT, CHR_linus, -30, 154, 0 }, // 13
    { SCENE_OP_MOVE_INSTANT, CHR_clio, -30, 154, 0 }, // 14
    { SCENE_OP_FOLLOW, CHR_clio, 1, 0, 0 }, // 15
    { SCENE_OP_ENABLE_SPELL, SPELL_THUNDER, 0, 0, 0 }, // 16
    { SCENE_OP_ENABLE_SPELL, SPELL_HIDE, 0, 0, 0 }, // 17
    { SCENE_OP_ENABLE_SPELL, SPELL_OPEN, 0, 0, 0 }, // 18
    { SCENE_OP_ENABLE_SPELL, SPELL_SLEEP, 0, 0, 0 }, // 19
    { SCENE_OP_MOVE, CHR_linus, 50, 154, 0 }, // 20
    { SCENE_OP_ANIM, CHR_linus, ANIM_IDLE, 0, 0 }, // 21
    { SCENE_OP_SAY_CLUSTER, ACT1_FOREST, A1_FOREST_SOME_TIME_LATER, 1, 0 }, // 22
    { SCENE_OP_CALL, HOOK_ACT1_FOREST_PAD_HINT, 0, 0, 0 }, // 23
    { SCENE_OP_CALL, HOOK_ACT1_FOREST_DAY, 0, 0, 0 }, // 24
    { SCENE_OP_SET, SCENE_FLAG_SCROLL, 1, 0, 0 }, // 25
    { SCENE_OP_SET, SCENE_FLAG_MOVEMENT, 1, 0, 0 }, // 26
    { SCENE_OP_SET, SCENE_FLAG_INTERFACE, 1, 0, 0 }, // 27
    { SCENE_OP_SET, SCENE_FLAG_SPELLS, 1, 0, 0 }, // 28
    { SCENE_OP_WAIT_SCROLL, 360, 0, 0, 0 }, // 29
    { SCENE_OP_CALL, HOOK_ACT1_FOREST_ENEMIES, 0, 0, 0 }, // 30
    { SCENE_OP_COMBAT, 0, 0, 0, 0 }, // 31
    { SCENE_OP_SET, SCENE_FLAG_INTERFACE, 0, 0, 0 }, // 32
    { SCENE_OP_SAY_CLUSTER, ACT1_FOREST, A1_FOREST_THATS_ALL, 1, 0 }, // 33
    { SCENE_OP_FADE_OUT, 120, 0, 0, 0 }, // 34
    { SCENE_OP_HARD_RESET, 0, 0, 0, 0 }, // 35
};

static const SceneStep act1_hall_steps[] = {
    { SCENE_OP_LEVEL, 5, 0, 0, 0 }, // 0
    { SCENE_OP_CHARACTER, CHR_linus, 0, 0, 0 }, // 1
    { SCENE_OP_CHARACTER, CHR_clio, 0, 0, 0 }, // 2
    { SCENE_OP_CHARACTER, CHR_xander, 0, 0, 0 }, // 3
    { SCENE_OP_MOVE_INSTANT, CHR_clio, 40, 174, 0 }, // 4
    { SCENE_OP_MOVE_INSTANT, CHR_linus, 360, 164, 0 }, // 5
    { SCENE_OP_LOOK, CHR_clio, 0, 0, 0 }, // 6
    { SCENE_OP_LOOK, CHR_linus, 1, 0, 0 }, // 7
    { SCENE_OP_SHOW, CHR_clio, 1, 0, 0 }, // 8
    { SCENE_OP_SHOW, CHR_linus, 1, 0, 0 }, // 9
    { SCENE_OP_SAY_CLUSTER, ACT1_HALL, A1_HALL_GUILD_YEAR, 1, 0 }, // 10
    { SCENE_OP_MOVE, CHR_linus, 200, 174, 0 }, // 11
    { SCENE_OP_SAY_CLUSTER, ACT1_HALL, A1_HALL_CLIO_LATE, 1, 0 }, // 12
    { SCENE_OP_MOVE, CHR_clio, 100, 154, 0 }, // 13
    { SCENE_OP_WAIT, 10, 0, 0, 0 }, // 14
    { SCENE_OP_LOOK, CHR_clio, 1, 0, 0 }, // 15
    { SCENE_OP_MOVE_INSTANT, CHR_xander, -30, 174, 0 }, // 16
    { SCENE_OP_SHOW, CHR_xander, 1, 0, 0 }, // 17
    { SCENE_OP_MOVE, CHR_xander, 40, 174, 0 }, // 18
    { SCENE_OP_SAY_CLUSTER, ACT1_HALL, A1_HALL_XANDER_AWAKE, 1, 0 }, // 19
    { SCENE_OP_CHOICE, ACT1_HALL_CHOICE, 0, 0, 0 }, // 20
    { SCENE_OP_SAY_RESPONSE, ACT1_HALL, A1_HALL_XANDER_ABILITY, 1, 0 }, // 21
    { SCENE_OP_BRANCH, 0, 24, 0, 0 }, // 22
    { SCENE_OP_GOTO, 25, 0, 0, 0 }, // 23
    { SCENE_OP_SAY, ACT1_HALL, A1_HALL_XANDER_WEAVE, 1, 0 }, // 24
    { SCENE_OP_SAY_CLUSTER, ACT1_HALL, A1_HALL_ENCARGO, 1, 0 }, // 25
    { SCENE_OP_CHOICE, ACT1_HALL_CHOICE, 1, 0, 0 }, // 26
    { SCENE_OP_LOOK, CHR_clio, 0, 0, 0 }, // 27
    { SCENE_OP_SAY_RESPONSE, ACT1_HALL, A1_HALL_CLIO_IF_XANDER_WANTS, 1, 0 }, // 28
    { SCENE_OP_SAY, ACT1_HALL, A1_HALL_CLIO_PREPARE, 1, 0 }, // 29
    { SCENE_OP_WAIT, 20, 0, 0, 0 }, // 30
    { SCENE_OP_NEXT_SCENE, SCENE_ACT1_COAST, 0, 0, 0 }, // 31
};

static const SceneStep act1_hut_steps[] = {
    { SCENE_OP_LEVEL, 6, 0, 0, 0 }, // 0
    { SCENE_OP_LIMITS, 0, 134, 275, 172 }, // 1
    { SCENE_OP_ITEM, 0, 28, 0, 0 }, // 2
    { SCENE_OP_ITEM, 1, 29, 0, 0 }, // 3
    { SCENE_OP_ITEM, 2, 30, 0, 0 }, // 4
    { SCENE_OP_SET, SCENE_FLAG_ROD, 0, 0, 0 }, // 5
    { SCENE_OP_CALL, HOOK_ACT1_HUT_START, 0, 0, 0 }, // 6
    { SCENE_OP_CHARACTER, CHR_linus, 0, 0, 0 }, // 7
    { SCENE_OP_CHARACTER, CHR_clio, 0, 0, 0 }, // 8
    { SCENE_OP_ACTIVE, CHR_linus, 0, 0, 0 }, // 9
    { SCENE_OP_MOVE_INSTANT, CHR_linus, -30, 160, 0 }, // 10
    { SCENE_OP_MOVE_INSTANT, CHR_clio, -60, 160, 0 }, // 11
    { SCENE_OP_FOLLOW, CHR_clio, 1, 0, 0 }, // 12
    { SCENE_OP_SHOW, CHR_linus, 1, 0, 0 }, // 13
    { SCENE_OP_SHOW, CHR_clio, 1, 0, 0 }, // 14
    { SCENE_OP_SAY_CLUSTER, ACT1_HUT, A1_HUT_ENTER, 1, 0 }, // 15
    { SCENE_OP_MOVE, CHR_linus, 50, 160, 0 }, // 16
    { SCENE_OP_SAY_CLUSTER, ACT1_HUT, A1_HUT_LOOM, 1, 0 }, // 17
    { SCENE_OP_SET, SCENE_FLAG_MOVEMENT, 1, 0, 0 }, // 18
    { SCENE_OP_SET, SCENE_FLAG_SCROLL, 1, 0, 0 }, // 19
    { SCENE_OP_CALL, HOOK_ACT1_HUT_ITEMS, 0, 0, 0 }, // 20
    { SCENE_OP_SET, SCENE_FLAG_MOVEMENT, 0, 0, 0 }, // 21
    { SCENE_OP_SET, SCENE_FLAG_SCROLL, 0, 0, 0 }, // 22
    { SCENE_OP_SAY_CLUSTER, ACT1_HUT, A1_HUT_STAFF, 1, 0 }, // 23
    { SCENE_OP_CALL, HOOK_ACT1_HUT_LIGHTNING, 0, 0, 0 }, // 24
    { SCENE_OP_SAY_CLUSTER, ACT1_HUT, A1_HUT_SYSTEM, 1, 0 }, // 25
    { SCENE_OP_SAY_CLUSTER, ACT1_HUT, A1_HUT_AWED, 1, 0 }, // 26
    { SCENE_OP_SAY_CLUSTER, ACT1_HUT, A1_HUT_BOBBIN, 1, 0 }, // 27
    { SCENE_OP_SAY_CLUSTER, ACT1_HUT, A1_HUT_LEAVE, 1, 0 }, // 28
    { SCENE_OP_CALL, HOOK_ACT1_HUT_SHADOW, 0, 0, 0 }, // 29
    { SCENE_OP_SAY, ACT1_HUT, A1_HUT_SHADOW, 1, 0 }, // 30
    { SCENE_OP_NEXT_SCENE, SCENE_ACT1_RETURN, 0, 0, 0 }, // 31
};

static const SceneStep act1_island_steps[] = {
    { SCENE_OP_LEVEL, 7, 0, 0, 0 }, // 0
    { SCENE_OP_LIMITS, 0, 134, 275, 172 }, // 1
    { SCENE_OP_ITEM, 0, 31, 0, 0 }, // 2
    { SCENE_OP_ITEM, 1, 32, 0, 0 }, // 3
    { SCENE_OP_ITEM, 2, 33, 0, 0 }, // 4
    { SCENE_OP_ITEM, 3, 34, 0, 0 }, // 5
    { SCENE_OP_ITEM, 4, 35, 0, 0 }, // 6
    { SCENE_OP_ITEM, 5, 36, 0, 0 }, // 7
    { SCENE_OP_ITEM, 6, 37, 0, 0 }, // 8
    { SCENE_OP_SET, SCENE_FLAG_ROD, 0, 0, 0 }, // 9
    { SCENE_OP_CHARACTER, CHR_linus, 0, 0, 0 }, // 10
    { SCENE_OP_CHARACTER, CHR_clio, 0, 0, 0 }, // 11
    { SCENE_OP_ACTIVE, CHR_linus, 0, 0, 0 }, // 12
    { SCENE_OP_MOVE_INSTANT, CHR_linus, -30, 154, 0 }, // 13
    { SCENE_OP_MOVE_INSTANT, CHR_clio, -60, 154, 0 }, // 14
    { SCENE_OP_FOLLOW, CHR_clio, 1, 0, 0 }, // 15
    { SCENE_OP_SHOW, CHR_linus, 1, 0, 0 }, // 16
    { SCENE_OP_SHOW, CHR_clio, 1, 0, 0 }, // 17
    { SCENE_OP_CALL, HOOK_ACT1_FDAY_START, 0, 0, 0 }, // 18
    { SCENE_OP_MOVE, CHR_linus, 50, 154, 0 }, // 19
    { SCENE_OP_SET, SCENE_FLAG_MOVEMENT, 1, 0, 0 }, // 20
    { SCENE_OP_SET, SCENE_FLAG_SCROLL, 1, 0, 0 }, // 21
    { SCENE_OP_WAIT_SCROLL, 200, 0, 0, 0 }, // 22
    { SCENE_OP_SAY_CLUSTER, ACT1_ISLAND, A1_ISLAND_COMBAT, 1, 0 }, // 23
    { SCENE_OP_CALL, HOOK_ACT1_FDAY_BOARS, 0, 0, 0 }, // 24
    { SCENE_OP_COMBAT, 0, 0, 0, 0 }, // 25
    { SCENE_OP_IF_DEFEATED, 36, 0, 0, 0 }, // 26
    { SCENE_OP_SAY_CLUSTER, ACT1_ISLAND, A1_ISLAND_HURT, 1, 0 }, // 27
    { SCENE_OP_CALL, HOOK_ACT1_FDAY_HEAL, 0, 0, 0 }, // 28
    { SCENE_OP_SAY_CLUSTER, ACT1_ISLAND, A1_ISLAND_HEALED, 1, 0 }, // 29
    { SCENE_OP_SET, SCENE_FLAG_MOVEMENT, 1, 0, 0 }, // 30
    { SCENE_OP_WAIT_SCROLL, 1000, 0, 0, 0 }, // 31
    { SCENE_OP_SAY_CLUSTER, ACT1_ISLAND, A1_ISLAND_ONWARD, 1, 0 }, // 32
    { SCENE_OP_SET, SCENE_FLAG_MOVEMENT, 1, 0, 0 }, // 33
    { SCENE_OP_WAIT_SCROLL, 1110, 0, 0, 0 }, // 34
    { SCENE_OP_NEXT_SCENE, SCENE_ACT1_HUT, 0, 0, 0 }, // 35
    { SCENE_OP_SAY, ACT1_ISLAND, A1_ISLAND_DEFEAT, 1, 0 }, // 36
    { SCENE_OP_GOTO, 23, 0, 0, 0 }, // 37
};

static const SceneStep act1_return_steps[] = {
    { SCENE_OP_LEVEL, 8, 0, 0, 0 }, // 0
    { SCENE_OP_LIMITS, 0, 134, 275, 172 }, // 1
    { SCENE_OP_SET, SCENE_FLAG_ROD, 1, 0, 0 }, // 2
    { SCENE_OP_CHARACTER, CHR_linus, 0, 0, 0 }, // 3
    { SCENE_OP_CHARACTER, CHR_clio, 0, 0, 0 }, // 4
    { SCENE_OP_ACTIVE, CHR_linus, 0, 0, 0 }, // 5
    { SCENE_OP_MOVE_INSTANT, CHR_linus, 350, 154, 0 }, // 6
    { SCENE_OP_MOVE_INSTANT, CHR_clio, 380, 154, 0 }, // 7
    { SCENE_OP_FOLLOW, CHR_clio, 1, 0, 0 }, // 8
    { SCENE_OP_SHOW, CHR_linus, 1, 0, 0 }, // 9
    { SCENE_OP_SHOW, CHR_clio, 1, 0, 0 }, // 10
    { SCENE_OP_ENABLE_SPELL, SPELL_THUNDER, 0, 0, 0 }, // 11
    { SCENE_OP_CALL, HOOK_ACT1_RETURN_START, 0, 0, 0 }, // 12
    { SCENE_OP_SAY_CLUSTER, ACT1_RETURN, A1_RETURN_START, 1, 0 }, // 13
    { SCENE_OP_MOVE, CHR_linus, 250, 154, 0 }, // 14
    { SCENE_OP_LOOK, CHR_linus, 1, 0, 0 }, // 15
    { SCENE_OP_SET, SCENE_FLAG_MOVEMENT, 1, 0, 0 }, // 16
    { SCENE_OP_SET, SCENE_FLAG_SCROLL, 1, 0, 0 }, // 17
    { SCENE_OP_SET, SCENE_FLAG_INTERFACE, 1, 0, 0 }, // 18
    { SCENE_OP_SET, SCENE_FLAG_SPELLS, 1, 0, 0 }, // 19
    { SCENE_OP_WAIT_SCROLL_L, 900, 0, 0, 0 }, // 20
    { SCENE_OP_SAY_CLUSTER, ACT1_RETURN, A1_RETURN_BOARS, 1, 0 }, // 21
    { SCENE_OP_CALL, HOOK_ACT1_RETURN_BOARS, 0, 0, 0 }, // 22
    { SCENE_OP_COMBAT, 0, 0, 0, 0 }, // 23
    { SCENE_OP_IF_DEFEATED, 35, 0, 0, 0 }, // 24
    { SCENE_OP_SAY_CLUSTER, ACT1_RETURN, A1_RETURN_BOARS_WON, 1, 0 }, // 25
    { SCENE_OP_SET, SCENE_FLAG_MOVEMENT, 1, 0, 0 }, // 26
    { SCENE_OP_WAIT_SCROLL_L, 400, 0, 0, 0 }, // 27
    { SCENE_OP_SAY_CLUSTER, ACT1_RETURN, A1_RETURN_GHOSTS, 1, 0 }, // 28
    { SCENE_OP_CALL, HOOK_ACT1_RETURN_GHOSTS, 0, 0, 0 }, // 29
    { SCENE_OP_COMBAT, 0, 0, 0, 0 }, // 30
    { SCENE_OP_IF_DEFEATED, 37, 0, 0, 0 }, // 31
    { SCENE_OP_SAY_CLUSTER, ACT1_RETURN, A1_RETURN_GHOSTS_WON, 1, 0 }, // 32
    { SCENE_OP_SAY_CLUSTER, ACT1_RETURN, A1_RETURN_DONE, 1, 0 }, // 33
    { SCENE_OP_NEXT_SCENE, SCENE_ACT1_COAST_END, 0, 0, 0 }, // 34
    { SCENE_OP_SAY, ACT1_RETURN, A1_RETURN_BOBBIN_HINT, 1, 0 }, // 35
    { SCENE_OP_GOTO, 21, 0, 0, 0 }, // 36
    { SCENE_OP_SAY, ACT1_RETURN, A1_RETURN_DEFEAT, 1, 0 }, // 37
    { SCENE_OP_GOTO, 28, 0, 0, 0 }, // 38
};

static const SceneStep act1_test_steps[] = {
    { SCENE_OP_LEVEL, 9, 0, 0, 0 }, // 0
    { SCENE_OP_LIMITS, 0, 134, 275, 172 }, // 1
    { SCENE_OP_SET, SCENE_FLAG_ROD, 1, 0, 0 }, // 2
    { SCENE_OP_CHARACTER, CHR_linus, 0, 0, 0 }, // 3
    { SCENE_OP_CHARACTER, CHR_clio, 0, 0, 0 }, // 4
    { SCENE_OP_ACTIVE, CHR_linus, 0, 0, 0 }, // 5
    { SCENE_OP_MOVE_INSTANT, CHR_linus, 140, 154, 0 }, // 6
    { SCENE_OP_SHOW, CHR_linus, 1, 0, 0 }, // 7
    { SCENE_OP_MOVE_INSTANT, CHR_clio, 70, 154, 0 }, // 8
    { SCENE_OP_ENABLE_SPELL, SPELL_THUNDER, 0, 0, 0 }, // 9
    { SCENE_OP_ENABLE_SPELL, SPELL_HIDE, 0, 0, 0 }, // 10
    { SCENE_OP_ENABLE_SPELL, SPELL_FIRE, 0, 0, 0 }, // 11
    { SCENE_OP_ENABLE_SPELL, SPELL_LIGHT, 0, 0, 0 }, // 12
    { SCENE_OP_SAY_CLUSTER, ACT1_TEST, A1_TEST_INTRO, 1, 0 }, // 13
    { SCENE_OP_WAIT_PRESS, 0, 0, 0, 0 }, // 14
    { SCENE_OP_SET, SCENE_FLAG_MOVEMENT, 1, 0, 0 }, // 15
    { SCENE_OP_SET, SCENE_FLAG_SCROLL, 1, 0, 0 }, // 16
    { SCENE_OP_SET, SCENE_FLAG_INTERFACE, 1, 0, 0 }, // 17
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_HUB, 0, 0 }, // 18
    { SCENE_OP_CHOICE, ACT1_TEST_HUB, 0, 0, 0 }, // 19
    { SCENE_OP_BRANCH, 0, 26, 0, 0 }, // 20
    { SCENE_OP_BRANCH, 1, 47, 0, 0 }, // 21
    { SCENE_OP_BRANCH, 2, 74, 0, 0 }, // 22
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_BYE, 1, 0 }, // 23
    { SCENE_OP_FADE_OUT, 60, 0, 0, 0 }, // 24
    { SCENE_OP_NEXT_SCENE, SCENE_ACT1_BEDROOM, 0, 0, 0 }, // 25
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_DLG_CLIO, 1, 0 }, // 26
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_DLG_XANDER, 1, 0 }, // 27
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_ANIM, 0, 0 }, // 28
    { SCENE_OP_ANIM, CHR_linus, ANIM_MAGIC, 0, 0 }, // 29
    { SCENE_OP_WAIT, 15, 0, 0, 0 }, // 30
    { SCENE_OP_ANIM, CHR_linus, ANIM_IDLE, 0, 0 }, // 31
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_QUIZ_Q1, 0, 0 }, // 32
    { SCENE_OP_CHOICE, ACT1_TEST_QUIZ, 0, 0, 0 }, // 33
    { SCENE_OP_BRANCH, 1, 37, 0, 0 }, // 34
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_QUIZ_BAD, 0, 0 }, // 35
    { SCENE_OP_GOTO, 32, 0, 0, 0 }, // 36
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_QUIZ_Q2, 0, 0 }, // 37
    { SCENE_OP_CHOICE, ACT1_TEST_QUIZ, 1, 0, 0 }, // 38
    { SCENE_OP_BRANCH, 2, 42, 0, 0 }, // 39
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_QUIZ_BAD, 0, 0 }, // 40
    { SCENE_OP_GOTO, 37, 0, 0, 0 }, // 41
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_QUIZ_CONF, 0, 0 }, // 42
    { SCENE_OP_CHOICE, ACT1_TEST_QUIZ, 2, 0, 0 }, // 43
    { SCENE_OP_BRANCH, 1, 37, 0, 0 }, // 44
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_QUIZ_OK, 1, 0 }, // 45
    { SCENE_OP_GOTO, 18, 0, 0, 0 }, // 46
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_DEMO_CAST, 0, 0 }, // 47
    { SCENE_OP_CAST, SPELL_SLEEP, 0, 0, 0 }, // 48
    { SCENE_OP_WAIT_SPELL, 0, 0, 0, 0 }, // 49
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_LIGHT_DEMO, 0, 0 }, // 50
    { SCENE_OP_CAST, SPELL_LIGHT, 0, 0, 0 }, // 51
    { SCENE_OP_WAIT_SPELL, 0, 0, 0, 0 }, // 52
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_PUZ_CHOICE, 0, 0 }, // 53
    { SCENE_OP_CHOICE, ACT1_TEST_CHOICE, 0, 0, 0 }, // 54
    { SCENE_OP_BRANCH, 1, 67, 0, 0 }, // 55
    { SCENE_OP_SAY_CLUSTER, ACT1_TEST, A1_TEST_PUZZLE_INTRO, 1, 0 }, // 56
    { SCENE_OP_ZONE, ZONE_CAULDRON, 0, 0, 0 }, // 57
    { SCENE_OP_SET, SCENE_FLAG_SPELLS, 1, 0, 0 }, // 58
    { SCENE_OP_PUZZLE_SEQ, 0, 0, 0, 0 }, // 59
    { SCENE_OP_WAIT_PUZZLE, 0, 0, 0, 0 }, // 60
    { SCENE_OP_IF_PUZZLE_SOLVED, 0, 63, 0, 0 }, // 61
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_NEVER, 0, 0 }, // 62
    { SCENE_OP_ZONE, ZONE_NONE, 0, 0, 0 }, // 63
    { SCENE_OP_SET, SCENE_FLAG_SPELLS, 0, 0, 0 }, // 64
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_PUZZLE_OK, 1, 0 }, // 65
    { SCENE_OP_GOTO, 18, 0, 0, 0 }, // 66
    { SCENE_OP_SAY_CLUSTER, ACT1_TEST, A1_TEST_PUZ2_INTRO, 1, 0 }, // 67
    { SCENE_OP_SET, SCENE_FLAG_SPELLS, 1, 0, 0 }, // 68
    { SCENE_OP_PUZZLE_SEQ, 1, 0, 0, 0 }, // 69
    { SCENE_OP_WAIT_PUZZLE, 1, 0, 0, 0 }, // 70
    { SCENE_OP_SET, SCENE_FLAG_SPELLS, 0, 0, 0 }, // 71
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_PUZZLE_OK, 1, 0 }, // 72
    { SCENE_OP_GOTO, 18, 0, 0, 0 }, // 73
    { SCENE_OP_SHOW, CHR_clio, 1, 0, 0 }, // 74
    { SCENE_OP_FOLLOW, CHR_clio, 1, 0, 0 }, // 75
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_COMBAT_MENU, 0, 0 }, // 76
    { SCENE_OP_CHOICE, ACT1_TEST_COMBAT_MENU, 0, 0, 0 }, // 77
    { SCENE_OP_BRANCH, 1, 97, 0, 0 }, // 78
    { SCENE_OP_BRANCH, 2, 18, 0, 0 }, // 79
    { SCENE_OP_SET, SCENE_FLAG_SPELLS, 1, 0, 0 }, // 80
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_COMBAT, 1, 0 }, // 81
    { SCENE_OP_CALL, HOOK_ACT1_TEST_GHOST, 0, 0, 0 }, // 82
    { SCENE_OP_COMBAT, 0, 0, 0, 0 }, // 83
    { SCENE_OP_IF_DEFEATED, 86, 0, 0, 0 }, // 84
    { SCENE_OP_GOTO, 88, 0, 0, 0 }, // 85
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_DEFEAT, 1, 0 }, // 86
    { SCENE_OP_GOTO, 81, 0, 0, 0 }, // 87
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_WAVE2, 1, 0 }, // 88
    { SCENE_OP_CALL, HOOK_ACT1_TEST_GHOST2, 0, 0, 0 }, // 89
    { SCENE_OP_COMBAT, 0, 0, 0, 0 }, // 90
    { SCENE_OP_IF_DEFEATED, 95, 0, 0, 0 }, // 91
    { SCENE_OP_SET, SCENE_FLAG_INTERFACE, 1, 0, 0 }, // 92
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_VICTORY, 1, 0 }, // 93
    { SCENE_OP_GOTO, 18, 0, 0, 0 }, // 94
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_DEFEAT, 1, 0 }, // 95
    { SCENE_OP_GOTO, 88, 0, 0, 0 }, // 96
    { SCENE_OP_SET, SCENE_FLAG_SPELLS, 0, 0, 0 }, // 97
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_MELEE, 1, 0 }, // 98
    { SCENE_OP_CALL, HOOK_ACT1_TEST_BOARS, 0, 0, 0 }, // 99
    { SCENE_OP_COMBAT, 0, 0, 0, 0 }, // 100
    { SCENE_OP_IF_DEFEATED, 106, 0, 0, 0 }, // 101
    { SCENE_OP_CALL, HOOK_ACT1_TEST_BOARS_AFTER, 0, 0, 0 }, // 102
    { SCENE_OP_SET, SCENE_FLAG_SPELLS, 1, 0, 0 }, // 103
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_VICTORY, 1, 0 }, // 104
    { SCENE_OP_GOTO, 18, 0, 0, 0 }, // 105
    { SCENE_OP_SAY, ACT1_TEST, A1_TEST_DEFEAT, 1, 0 }, // 106
    { SCENE_OP_GOTO, 99, 0, 0, 0 }, // 107
};

const SceneScript scenes[] = {
    { "act1_bedroom", act1_bedroom_steps, 18 },
    { "act1_coast", act1_coast_steps, 22 },
    { "act1_coast_end", act1_coast_end_steps, 24 },
    { "act1_corridor", act1_corridor_steps, 23 },
    { "act1_forest", act1_forest_steps, 36 },
    { "act1_hall", act1_hall_steps, 32 },
    { "act1_hut", act1_hut_steps, 32 },
    { "act1_island", act1_island_steps, 38 },
    { "act1_return", act1_return_steps, 39 },
    { "act1_test", act1_test_steps, 108 },
};

const u8 scene_count = 10;

const PuzzleSeq puzzle_seqs[] = {
    { 3, {SPELL_THUNDER, SPELL_FIRE, SPELL_HIDE}, {0, 0, 0} }, // 0: act1_test:puerta_test
    { 3, {SPELL_THUNDER, SPELL_LIGHT, SPELL_HIDE}, {0, 1, 0} }, // 1: act1_test:eco_test
};

const SceneLevel scene_levels[] = {
    { &bedroom_bg_tile, &bedroom_bg_map, &bedroom_front_tile, &bedroom_front_map, &bedroom_night_pal, SCREEN_WIDTH, BG_SCRL_AUTO_RIGHT, 3 }, // 0
    { &coast_bg_tile, &coast_bg_map, &coast_front_tile, &coast_front_map, &coast_pal, 640, BG_SCRL_USER_RIGHT, 3 }, // 1
    { &coast_bg_tile, &coast_bg_map, &coast_front_tile, &coast_front_map, &coast_storm_pal, 640, BG_SCRL_USER_RIGHT, 3 }, // 2
    { NULL, NULL, &historians_corridor_front_tile, &historians_corridor_front_map, &historians_corridor_pal, 800, BG_SCRL_USER_LEFT, 0 }, // 3
    { &forest_bg_tile, &forest_bg_map, &forest_front_tile, &forest_front_map, &forest_dark_pal, 1440, BG_SCRL_USER_RIGHT, 3 }, // 4
    { &historians_bg_tile, &historians_bg_map, &historians_front_tile, &historians_front_map, &historians_pal, SCREEN_WIDTH, BG_SCRL_AUTO_RIGHT, 3 }, // 5
    { &hut_bg_tile, &hut_bg_map, &hut_front_tile, &hut_front_map, &hut_pal, 640, BG_SCRL_USER_RIGHT, 3 }, // 6
    { &forest_bg_tile, &forest_bg_map, &forest_front_tile, &forest_front_map, &forest_pal, 1440, BG_SCRL_USER_RIGHT, 3 }, // 7
    { &forest_bg_tile, &forest_bg_map, &forest_front_tile, &forest_front_map, &forest_dark_pal, 1440, BG_SCRL_USER_LEFT, 3 }, // 8
    { &forest_bg_tile, &forest_bg_map, &forest_front_tile, &forest_front_map, &forest_pal, 1440, BG_SCRL_USER_RIGHT, 3 }, // 9
};

const SceneItem scene_items[] = {
    { &item_bedroom_bed, PAL0, 31, 139, 93, 0, 23, 0, FORCE_BACKGROUND }, // 0
    { &item_bedroom_chair, PAL0, 236, 110, 26, 0, 43, 0, FORCE_BACKGROUND }, // 1
    { &item_bedroom_windowsill, PAL0, 125, 121, 99, 0, 22, 0, FORCE_BACKGROUND }, // 2
    { &item_bedroom_cabinet, PAL0, 270, 79, 51, 0, 82, 0, FORCE_BACKGROUND }, // 3
    { &item_bedroom_linus_sleeping, PAL0, 30, 112, 0, 0, 0, 0, FORCE_BACKGROUND }, // 4
    { &item_bedroom_portrait, PAL0, 4, 120, 27, 0, 23, 39, FORCE_BACKGROUND }, // 5
    { &item_bedroom_chest, PAL0, 176, 148, 40, 0, 7, 17, CALCULATE_DEPTH }, // 6
    { &item_coast_seagull, PAL0, 520, 112, 0, 0, 0, 0, FORCE_BACKGROUND }, // 7
    { &item_coast_leaves, PAL0, 478, 156, 24, 0, 8, 8, CALCULATE_DEPTH }, // 8
    { &item_corridor_bookpedestal_sprite, PAL0, 600, 95, COLLISION_DEFAULT, COLLISION_DEFAULT, 8, 58, CALCULATE_DEPTH }, // 9
    { &item_corridor_bookpedestal_sprite, PAL0, 200, 95, COLLISION_DEFAULT, COLLISION_DEFAULT, 8, 58, CALCULATE_DEPTH }, // 10
    { &item_corridor_lamp_sprite, PAL0, 32, 0, 0, 0, 0, 0, FORCE_BACKGROUND }, // 11
    { &item_corridor_lamp_sprite, PAL0, 176, 0, 0, 0, 0, 0, FORCE_BACKGROUND }, // 12
    { &item_corridor_lamp_sprite, PAL0, 336, 0, 0, 0, 0, 0, FORCE_BACKGROUND }, // 13
    { &item_corridor_lamp_sprite, PAL0, 464, 0, 0, 0, 0, 0, FORCE_BACKGROUND }, // 14
    { &item_corridor_lamp_sprite, PAL0, 656, 0, 0, 0, 0, 0, FORCE_BACKGROUND }, // 15
    { &item_corridor_door_bottom_sprite, PAL0, 96, 120, COLLISION_DEFAULT, COLLISION_DEFAULT, COLLISION_DEFAULT, COLLISION_DEFAULT, FORCE_BACKGROUND }, // 16
    { &item_corridor_door_bottom_sprite, PAL0, 400, 120, COLLISION_DEFAULT, COLLISION_DEFAULT, COLLISION_DEFAULT, COLLISION_DEFAULT, FORCE_BACKGROUND }, // 17
    { &item_corridor_door_bottom_sprite, PAL0, 720, 120, COLLISION_DEFAULT, COLLISION_DEFAULT, COLLISION_DEFAULT, COLLISION_DEFAULT, FORCE_BACKGROUND }, // 18
    { &item_corridor_map_bottom_sprite, PAL0, 240, 120, COLLISION_DEFAULT, COLLISION_DEFAULT, COLLISION_DEFAULT, COLLISION_DEFAULT, FORCE_BACKGROUND }, // 19
    { &item_corridor_map_bottom_sprite, PAL0, 544, 120, COLLISION_DEFAULT, COLLISION_DEFAULT, COLLISION_DEFAULT, COLLISION_DEFAULT, FORCE_BACKGROUND }, // 20
    { &item_forest_fg1_sprite, PAL0, 260, 160, 0, 0, 0, 0, FORCE_FOREGROUND }, // 21
    { &item_forest_fg5_sprite, PAL0, 180, 0, 0, 0, 0, 0, FORCE_FOREGROUND }, // 22
    { &item_forest_fg2_sprite, PAL0, 440, 152, 0, 0, 0, 0, FORCE_FOREGROUND }, // 23
    { &item_forest_fg3_sprite, PAL0, 880, 160, 0, 0, 0, 0, FORCE_FOREGROUND }, // 24
    { &item_forest_fg4_sprite, PAL0, 1400, 104, 0, 0, 0, 0, FORCE_FOREGROUND }, // 25
    { &item_forest_fg1_sprite, PAL0, 1050, 160, 0, 0, 0, 0, FORCE_FOREGROUND }, // 26
    { &item_forest_fg5_sprite, PAL0, 1270, 0, 0, 0, 0, 0, FORCE_FOREGROUND }, // 27
    { &item_hut_staff, PAL0, 430, 150, 40, 0, 10, 8, CALCULATE_DEPTH }, // 28
    { &item_hut_loom_debris, PAL0, 200, 110, 48, 0, 6, 16, FORCE_BACKGROUND }, // 29
    { &item_hut_threads, PAL0, 500, 146, 32, 0, 8, 12, CALCULATE_DEPTH }, // 30
    { &item_forest_fg1_sprite, PAL0, 260, 160, 0, 0, 0, 0, FORCE_FOREGROUND }, // 31
    { &item_forest_fg5_sprite, PAL0, 180, 0, 0, 0, 0, 0, FORCE_FOREGROUND }, // 32
    { &item_forest_fg2_sprite, PAL0, 440, 152, 0, 0, 0, 0, FORCE_FOREGROUND }, // 33
    { &item_forest_fg3_sprite, PAL0, 880, 160, 0, 0, 0, 0, FORCE_FOREGROUND }, // 34
    { &item_forest_fg4_sprite, PAL0, 1400, 104, 0, 0, 0, 0, FORCE_FOREGROUND }, // 35
    { &item_forest_fg1_sprite, PAL0, 1050, 160, 0, 0, 0, 0, FORCE_FOREGROUND }, // 36
    { &item_forest_fg5_sprite, PAL0, 1270, 0, 0, 0, 0, 0, FORCE_FOREGROUND }, // 37
};

const ScenePalette scene_palettes[] = {
    { &swan_pal }, // 0
};

s16 scene_id_by_name(const char *name)    // SceneId, o -1 si no existe
{
    for (u8 i = 0; i < scene_count; i++)
        if (strcmp(scenes[i].name, name) == 0) return i;
    return -1;
}
