// Generated by tools/gen_scenes.py from data/scenes/*.scene — DO NOT EDIT
#include <genesis.h>
#include "scenes/scene_vm.h"
#include "scenes/scene_data.h"
#include "scenes/scene_hooks.h"
#include "narrative/texts_data.h"
#include "narrative/choices_data.h"
#include "actors/characters.h"
#include "spells/constants_spells.h"

static const SceneStep act1_bedroom_steps[] = {
    { SCENE_OP_CALL, HOOK_ACT1_BEDROOM_SETUP, 0, 0, 0 }, // 0
    { SCENE_OP_CALL, HOOK_ACT1_BEDROOM_SWAN, 0, 0, 0 }, // 1
    { SCENE_OP_CALL, HOOK_ACT1_BEDROOM_WAKE, 0, 0, 0 }, // 2
    { SCENE_OP_CALL, HOOK_ACT1_BEDROOM_ITEMS, 0, 0, 0 }, // 3
    { SCENE_OP_SAY, ACT1_BEDROOM, A1_BEDROOM_MOTHER_CALLS, 1, 0 }, // 4
    { SCENE_OP_SAY, ACT1_BEDROOM, A1_BEDROOM_TOO_LATE, 0, 0 }, // 5
    { SCENE_OP_NEXT_SCENE, SCENE_ACT1_CORRIDOR, 0, 0, 0 }, // 6
};

static const SceneStep act1_corridor_steps[] = {
    { SCENE_OP_CALL, HOOK_ACT1_CORRIDOR_SETUP, 0, 0, 0 }, // 0
    { SCENE_OP_SAY_CLUSTER, SYSTEM_DIALOG, SYSMSG_DEMO_TITLE, 1, 0 }, // 1
    { SCENE_OP_CALL, HOOK_ACT1_CORRIDOR_ENTRY, 0, 0, 0 }, // 2
    { SCENE_OP_SAY_CLUSTER, ACT1_CORRIDOR, A1_CORRIDOR_OVERSLEPT, 0, 0 }, // 3
    { SCENE_OP_SET, SCENE_FLAG_SCROLL, 1, 0, 0 }, // 4
    { SCENE_OP_SET, SCENE_FLAG_MOVEMENT, 1, 0, 0 }, // 5
    { SCENE_OP_CALL, HOOK_ACT1_CORRIDOR_ITEMS, 0, 0, 0 }, // 6
    { SCENE_OP_NEXT_SCENE, SCENE_ACT1_HALL, 0, 0, 0 }, // 7
};

static const SceneStep act1_forest_steps[] = {
    { SCENE_OP_CALL, HOOK_ACT1_FOREST_SETUP, 0, 0, 0 }, // 0
    { SCENE_OP_SAY_CLUSTER, ACT1_FOREST, A1_FOREST_SOME_TIME_LATER, 1, 0 }, // 1
    { SCENE_OP_CALL, HOOK_ACT1_FOREST_PAD_HINT, 0, 0, 0 }, // 2
    { SCENE_OP_CALL, HOOK_ACT1_FOREST_DAY, 0, 0, 0 }, // 3
    { SCENE_OP_SET, SCENE_FLAG_SCROLL, 1, 0, 0 }, // 4
    { SCENE_OP_SET, SCENE_FLAG_MOVEMENT, 1, 0, 0 }, // 5
    { SCENE_OP_SET, SCENE_FLAG_INTERFACE, 1, 0, 0 }, // 6
    { SCENE_OP_SET, SCENE_FLAG_SPELLS, 1, 0, 0 }, // 7
    { SCENE_OP_WAIT_SCROLL, 360, 0, 0, 0 }, // 8
    { SCENE_OP_CALL, HOOK_ACT1_FOREST_ENEMIES, 0, 0, 0 }, // 9
    { SCENE_OP_COMBAT, 0, 0, 0, 0 }, // 10
    { SCENE_OP_SET, SCENE_FLAG_INTERFACE, 0, 0, 0 }, // 11
    { SCENE_OP_SAY_CLUSTER, ACT1_FOREST, A1_FOREST_THATS_ALL, 1, 0 }, // 12
    { SCENE_OP_FADE_OUT, 120, 0, 0, 0 }, // 13
    { SCENE_OP_HARD_RESET, 0, 0, 0, 0 }, // 14
};

static const SceneStep act1_hall_steps[] = {
    { SCENE_OP_CALL, HOOK_ACT1_HALL_SETUP, 0, 0, 0 }, // 0
    { SCENE_OP_SAY_CLUSTER, ACT1_HALL, A1_HALL_GUILD_YEAR, 1, 0 }, // 1
    { SCENE_OP_MOVE, CHR_linus, 200, 174, 0 }, // 2
    { SCENE_OP_SAY_CLUSTER, ACT1_HALL, A1_HALL_CLIO_LATE, 1, 0 }, // 3
    { SCENE_OP_MOVE, CHR_clio, 100, 154, 0 }, // 4
    { SCENE_OP_WAIT, 10, 0, 0, 0 }, // 5
    { SCENE_OP_LOOK, CHR_clio, 1, 0, 0 }, // 6
    { SCENE_OP_MOVE_INSTANT, CHR_xander, -30, 174, 0 }, // 7
    { SCENE_OP_SHOW, CHR_xander, 1, 0, 0 }, // 8
    { SCENE_OP_MOVE, CHR_xander, 40, 174, 0 }, // 9
    { SCENE_OP_SAY_CLUSTER, ACT1_HALL, A1_HALL_XANDER_AWAKE, 1, 0 }, // 10
    { SCENE_OP_CHOICE, ACT1_HALL_CHOICE, 0, 0, 0 }, // 11
    { SCENE_OP_SAY_RESPONSE, ACT1_HALL, A1_HALL_XANDER_ABILITY, 1, 0 }, // 12
    { SCENE_OP_SAY_CLUSTER, ACT1_HALL, A1_HALL_XANDER_FATHER_WANTED, 1, 0 }, // 13
    { SCENE_OP_CHOICE, ACT1_HALL_CHOICE, 1, 0, 0 }, // 14
    { SCENE_OP_LOOK, CHR_clio, 0, 0, 0 }, // 15
    { SCENE_OP_SAY_RESPONSE, ACT1_HALL, A1_HALL_CLIO_IF_XANDER_WANTS, 1, 0 }, // 16
    { SCENE_OP_WAIT, 20, 0, 0, 0 }, // 17
    { SCENE_OP_NEXT_SCENE, SCENE_ACT1_FOREST, 0, 0, 0 }, // 18
};

const SceneScript scenes[] = {
    { "act1_bedroom", act1_bedroom_steps, 7 },
    { "act1_corridor", act1_corridor_steps, 8 },
    { "act1_forest", act1_forest_steps, 15 },
    { "act1_hall", act1_hall_steps, 19 },
};

const u8 scene_count = 4;

s16 scene_id_by_name(const char *name)    // SceneId, o -1 si no existe
{
    for (u8 i = 0; i < scene_count; i++)
        if (strcmp(scenes[i].name, name) == 0) return i;
    return -1;
}
