// Generated by tools/gen_scenes.py from data/scenes/*.scene — DO NOT EDIT
#ifndef _SCENE_DATA_H_
#define _SCENE_DATA_H_

#include "scenes/scene_vm.h"

typedef enum {
    SCENE_ACT1_BEDROOM = 0,
    SCENE_ACT1_COAST = 1,
    SCENE_ACT1_COAST_END = 2,
    SCENE_ACT1_CORRIDOR = 3,
    SCENE_ACT1_FOREST = 4,
    SCENE_ACT1_HALL = 5,
    SCENE_ACT1_HUT = 6,
    SCENE_ACT1_RETURN = 7,
    SCENE_ACT1_TEST = 8,
    SCENE_COUNT_TOTAL = 9
} SceneId;

extern const SceneScript scenes[];
extern const u8 scene_count;

s16 scene_id_by_name(const char *name); // SceneId, o -1 si no existe (para hacks/smoke)

extern const PuzzleSeq puzzle_seqs[]; // secuencias de puzzle (indexadas por los ops PUZZLE_*)
extern const SceneLevel   scene_levels[];   // niveles (indexados por el op LEVEL)
extern const SceneItem    scene_items[];    // items del escenario (indexados por el op ITEM)
extern const ScenePalette scene_palettes[]; // paletas a cargar (indexadas por el op PALETTE)

#endif // _SCENE_DATA_H_
