// Generated by tools/gen_scenes.py from data/scenes/*.scene — DO NOT EDIT
#ifndef _SCENE_DATA_H_
#define _SCENE_DATA_H_

#include "scenes/scene_vm.h"

typedef enum {
    SCENE_ACT1_SCENE1 = 0,
    SCENE_ACT1_SCENE2 = 1,
    SCENE_ACT1_SCENE3 = 2,
    SCENE_ACT1_SCENE5 = 3,
    SCENE_COUNT_TOTAL = 4
} SceneId;

extern const SceneScript scenes[];
extern const u8 scene_count;

const SceneScript* scene_lookup(u8 act, u8 scene); // NULL si no existe

#endif // _SCENE_DATA_H_
