#!/usr/bin/env python3
# gen_choices.py – convierte data/choices.csv en src/narrative/choices_data.{h,c}
# Ejecutar desde la raíz del repo: python3 tools/gen_choices.py
#
# Formato del CSV: set,item,face,side,time,es_1..es_4,en_1..en_4
# (columnas de opción vacías = opción inexistente; num_options se calcula)
import csv
import sys
from collections import OrderedDict

CSV_FILE    = 'data/choices.csv'
HEADER_FILE = 'src/narrative/choices_data.h'
SOURCE_FILE = 'src/narrative/choices_data.c'

def die(msg):
    print(f"gen_choices.py: ERROR: {msg}", file=sys.stderr)
    sys.exit(1)

def c_escape(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')

# 1. Leer choices.csv agrupando por set
sets = OrderedDict()   # set_name -> list of rows (ordenadas por item)
with open(CSV_FILE, newline='', encoding='utf-8') as f:
    for row in csv.DictReader(f):
        name = row['set'].strip()
        if not name:
            continue
        sets.setdefault(name, []).append(row)

for name, rows in sets.items():
    rows.sort(key=lambda r: int(r['item']))
    for expected, row in enumerate(rows):
        if int(row['item']) != expected:
            die(f"set '{name}': items no consecutivos (falta el {expected})")

# 2. Generar choices_data.h
with open(HEADER_FILE, 'w', encoding='utf-8') as h:
    h.write('// Generated by tools/gen_choices.py from data/choices.csv — DO NOT EDIT\n')
    h.write('#ifndef _CHOICES_DATA_H_\n#define _CHOICES_DATA_H_\n\n')
    h.write('#include "narrative/texts.h"\n\n')
    h.write('// Choice sets (índices en choices[])\n')
    for i, name in enumerate(sets):
        h.write(f'#define {name.upper()}    {i}\n')
    h.write('\nextern const ChoiceItem *choices[];\n')
    h.write('\n#endif // _CHOICES_DATA_H_\n')

# 3. Generar choices_data.c
with open(SOURCE_FILE, 'w', encoding='utf-8') as c:
    c.write('// Generated by tools/gen_choices.py from data/choices.csv — DO NOT EDIT\n')
    c.write('#include <genesis.h>\n')
    c.write('#include "narrative/texts.h"\n')
    c.write('#include "narrative/choices_data.h"\n')
    c.write('#include "narrative/dialogs.h"\n')
    c.write('#include "actors/characters.h"\n\n')

    for name, rows in sets.items():
        c.write(f'const ChoiceItem {name}[] = {{\n')
        for row in rows:
            es = [row[f'es_{i}'].strip() for i in range(1, 5)]
            en = [row[f'en_{i}'].strip() for i in range(1, 5)]
            n_es = sum(1 for o in es if o)
            n_en = sum(1 for o in en if o)
            if n_es != n_en:
                die(f"set '{name}' item {row['item']}: {n_es} opciones ES vs {n_en} EN")
            if n_es == 0:
                die(f"set '{name}' item {row['item']}: sin opciones")
            es_str = ', '.join(f'"{c_escape(o)}"' for o in es if o)
            en_str = ', '.join(f'"{c_escape(o)}"' for o in en if o)
            c.write(f"    {{{row['face'].strip()}, {row['side'].strip()}, {row['time'].strip()}, {n_es},\n")
            c.write(f'        {{{{ {es_str}}},\n')
            c.write(f'        {{ {en_str}}}}}}},\n')
        c.write('    {0, SIDE_LEFT, DEFAULT_TALK_TIME, 0, {{NULL}}} // Terminator\n')
        c.write('};\n\n')

    c.write('const ChoiceItem *choices[] = {\n')
    for i, name in enumerate(sets):
        c.write(f'    {name},   // {i}\n')
    c.write('};\n')

print('✓ Archivos generados:')
print(f'  • {HEADER_FILE}')
print(f'  • {SOURCE_FILE}')
