// Auto-generated from texts.csv and clusters.csv – DO NOT EDIT
#ifndef TEXTS_GENERATED_H
#define TEXTS_GENERATED_H

enum SystemDialogId {
    SYSMSG_CANT_USE_PATTERN = 0,
    SYSMSG_DEMO_TITLE = 1,
    SYSMSG_DISCLAIMER = 2,
    SYSMSG_COUNT = 3
};

enum Act1Dialog1Id {
    A1D1_OVERSLEPT = 0,
    A1D1_CORRIDOR_MEMORIES = 1,
    A1D1_REVISIT_MEMORIES = 2,
    A1D1_BOOK_HISTORY = 3,
    A1D1_BOOK_ENDS_WITH_FATHER = 4,
    A1D1_BOOK_MOTHER_WRITES_NEXT = 5,
    A1D1_MYTH_COLLECTION = 6,
    A1D1_MYTH_PASTORS = 7,
    A1D1_COUNT = 8
};

enum Act1Dialog2Id {
    A1D2_GUILD_YEAR = 0,
    A1D2_MONDAY_MORNING = 1,
    A1D2_CLIO_LATE = 2,
    A1D2_LINUS_STRANGEST_DREAM = 3,
    A1D2_SWAN_CAME = 4,
    A1D2_CLIO_TELL_LATER = 5,
    A1D2_XANDER_AWAKE = 6,
    A1D2_LINUS_FORGIVE = 7,
    A1D2_XANDER_YOUR_FATHERS_SON = 8,
    A1D2_XANDER_UNFULFILLED = 9,
    A1D2_LINUS_WHICH_STORY = 10,
    A1D2_XANDER_ISLAND_LEGEND = 11,
    A1D2_XANDER_ABILITY = 12,
    A1D2_XANDER_NOT_LEGEND = 13,
    A1D2_XANDER_VANISHED = 14,
    A1D2_XANDER_FATHER_WANTED = 15,
    A1D2_CLIO_DESTINY = 16,
    A1D2_XANDER_LINUS_AGE = 17,
    A1D2_XANDER_FATHERS_AGE = 18,
    A1D2_XANDER_BEFORE_JOINED = 19,
    A1D2_LINUS_MOTHER = 20,
    A1D2_CLIO_IF_XANDER_WANTS = 21,
    A1D2_CLIO_I_WONT_LET_YOU = 22,
    A1D2_COUNT = 23
};

enum Act1Dialog3Id {
    A1D3_SOME_TIME_LATER = 0,
    A1D3_ENEMIES_APPROACHING = 1,
    A1D3_THAT_HURTS = 2,
    A1D3_THINK_BACKWARDS = 3,
    A1D3_TRY_HIDE_OR_THUNDER = 4,
    A1D3_REVERSE_NOTES_COUNTER = 5,
    A1D3_CANT_CAST_WHILE_HIDDEN = 6,
    A1D3_NOTE_ABOUT_SCENE = 7,
    A1D3_DEMO_REASON = 8,
    A1D3_PRESS_START = 9,
    A1D3_THATS_ALL = 10,
    A1D3_THANKS_FOR_PLAYING = 11,
    A1D3_TURN_OFF_CONSOLE = 12,
    A1D3_ORGANIZE_SOCKS = 13,
    A1D3_COUNT = 14
};

enum Act1Dialog4Id {
    A1D4_HUNDRED_YEARS = 0,
    A1D4_CANT_STOP_LONG = 1,
    A1D4_NEXT_MORNING = 2,
    A1D4_SLEPT_BAD = 3,
    A1D4_NOT_REAL = 4,
    A1D4_NO_TIME_TO_SIT = 5,
    A1D4_LULLABY = 6,
    A1D4_LEARNED_PATTERN = 7,
    A1D4_ENTER_PAUSE_MENU = 8,
    A1D4_MOTHER_CALLS = 9,
    A1D4_TOO_LATE = 10,
    A1D4_COUNT = 11
};

enum DialogSetId {
    SYSTEM_DIALOG,  // 0
    ACT1_DIALOG1,  // 1
    ACT1_DIALOG2,  // 2
    ACT1_DIALOG3,  // 3
    ACT1_DIALOG4,  // 4
    DIALOG_SET_COUNT
};

#endif // TEXTS_GENERATED_H
