// Auto-generated from texts.csv and clusters.csv
#ifndef TEXTS_GENERATED_H
#define TEXTS_GENERATED_H

enum SystemDialogId {
    SYSMSG_CANT_USE_PATTERN = 0,
    SYSMSG_DEMO_TITLE = 1,
    SYSMSG_DISCLAIMER = 2,
    SYSMSG_COUNT = 3
};

enum Act1Dialog1Id {
    A1D1_OVERSLEPT = 0,
    A1D1_CORRIDOR_MEMORIES = 1,
    A1D1_REVISIT_MEMORIES = 2,
    A1D1_BOOK_HISTORY = 3,
    A1D1_BOOK_ENDS_WITH_FATHER = 4,
    A1D1_BOOK_MOTHER_WRITES_NEXT = 5,
    A1D1_MYTH_COLLECTION = 6,
    A1D1_MYTH_PASTORS = 7,
    A1D1_COUNT = 8
};

enum Act1Dialog2Id {
    A1D2_GUILD_YEAR = 0,
    A1D2_MONDAY = 1,
    A1D2_CLIO_LATE = 2,
    A1D2_LINUS_STRANGE_DREAM = 3,
    A1D2_LINUS_SWAN_ROOM = 4,
    A1D2_CLIO_LATER = 5,
    A1D2_XANDER_AWAKE = 6,
    A1D2_LINUS_FORGIVE = 7,
    A1D2_XANDER_FATHER_SON = 8,
    A1D2_XANDER_UNACHIEVED = 9,
    A1D2_LINUS_WHICH_ONE = 10,
    A1D2_XANDER_WEAVERS_ISLAND = 11,
    A1D2_XANDER_LEGEND = 12,
    A1D2_XANDER_NO_LEGEND = 13,
    A1D2_XANDER_VANISHED = 14,
    A1D2_XANDER_FATHER_WANTED = 15,
    A1D2_CLIO_DESTINY = 16,
    A1D2_XANDER_LINUS_AGE = 17,
    A1D2_XANDER_FATHER_AGE = 18,
    A1D2_XANDER_ONE_YEAR_BEFORE = 19,
    A1D2_LINUS_MOTHER = 20,
    A1D2_CLIO_IF_XANDER_WANTS = 21,
    A1D2_CLIO_NO_TRAVEL = 22,
    A1D2_COUNT = 23
};

enum Act1Dialog3Id {
    A1D3_SOME_TIME_LATER = 0,
    A1D3_ENEMIES_APPROACH = 1,
    A1D3_THAT_HURTS = 2,
    A1D3_THINK_BACKWARDS = 3,
    A1D3_THANKS_FOR_PLAYING = 4,
    A1D3_TURN_OFF_CONSOLE = 5,
    A1D3_ORGANIZE_SOCKS = 6,
    A1D3_THATS_ALL = 7,
    A1D3_NOTE_ABOUT_SCENE = 8,
    A1D3_DEMO_REASON = 9,
    A1D3_PRESS_START = 10,
    A1D3_COUNT = 11
};

enum Act1Dialog4Id {
    A1D4_HUNDRED_YEARS = 0,
    A1D4_CANT_STOP_LONG = 1,
    A1D4_NEXT_MORNING = 2,
    A1D4_BAD_SLEEP = 3,
    A1D4_NOT_REAL = 4,
    A1D4_NO_TIME_SIT = 5,
    A1D4_LULLABY = 6,
    A1D4_LEARNED_PATTERN = 7,
    A1D4_PAUSE_MENU = 8,
    A1D4_WHERE_ARE_YOU = 9,
    A1D4_TOO_LATE = 10,
    A1D4_COUNT = 11
};

enum DialogClusterId {
    CLUSTER_SYS_DEMO_WARNING,
    CLUSTER_ACT1_SWAN_INTRO,
    CLUSTER_ACT1_MORNING,
    CLUSTER_ACT1_LEARNED_PATTERN,
    CLUSTER_ACT1_EXIT,
    CLUSTER_ACT1_INTRO,
    CLUSTER_ACT1_REVISIT,
    CLUSTER_ACT1_BOOK_HISTORY,
    CLUSTER_ACT1_MYTHS,
    CLUSTER_A1D2_START,
    CLUSTER_A1D2_CLIO_LATE,
    CLUSTER_A1D2_XANDER_ENTRANCE,
    CLUSTER_A1D2_LEGEND,
    CLUSTER_A1D2_AFTER_RESPONSE,
    CLUSTER_A1D2_CHOICE_REPLY,
    CLUSTER_A1D3_ENDING,
    CLUSTER_COUNT
};

#endif
